// <auto-generated/>
#nullable enable


using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
namespace Matrix.RustSdk.Bindings;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public int capacity;
    public int len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref RustCallStatus status) => {
            var buffer = _UniFFILib.ffi_matrix_sdk_ffi_rustbuffer_alloc(size, ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref RustCallStatus status) => {
            _UniFFILib.ffi_matrix_sdk_ffi_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, int length) {
        unsafe {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream() {
        unsafe {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), len));
        }
    }

    public BigEndianStream AsWriteableStream() {
        unsafe {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), capacity, capacity, FileAccess.Write));
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToInt32(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct RustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException: Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

public class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

public class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

public class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

public class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

public class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

public class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

public class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref RustCallStatus status);
    public delegate U RustCallFunc<out U>(ref RustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new RustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref RustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref RustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: Exception {
    public StreamUnderflowException() {
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - stream.Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] value) {
        stream.Write(value, 0, value.Length);
    }

    public void WriteByte(byte value) {
        stream.WriteByte(value);
    }

    public void WriteUShort(ushort value) {
        stream.WriteByte((byte)(value >> 8));
        stream.WriteByte((byte)value);
    }

    public void WriteUInt(uint value) {
        stream.WriteByte((byte)(value >> 24));
        stream.WriteByte((byte)(value >> 16));
        stream.WriteByte((byte)(value >> 8));
        stream.WriteByte((byte)value);
    }

    public void WriteULong(ulong value) {
        WriteUInt((uint)(value >> 32));
        WriteUInt((uint)value);
    }

    public void WriteSByte(sbyte value) {
        stream.WriteByte((byte)value);
    }

    public void WriteShort(short value) {
        WriteUShort((ushort)value);
    }

    public void WriteInt(int value) {
        WriteUInt((uint)value);
    }

    public void WriteFloat(float value) {
        WriteInt(BitConverter.SingleToInt32Bits(value));
    }

    public void WriteLong(long value) {
        WriteULong((ulong)value);
    }

    public void WriteDouble(double value) {
        WriteLong(BitConverter.DoubleToInt64Bits(value));
    }

    public byte[] ReadBytes(int length) {
        CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() {
        CheckRemaining(1);
        return Convert.ToByte(stream.ReadByte());
    }

    public ushort ReadUShort() {
        CheckRemaining(2);
        return (ushort)(stream.ReadByte() << 8 | stream.ReadByte());
    }

    public uint ReadUInt() {
        CheckRemaining(4);
        return (uint)(stream.ReadByte() << 24
            | stream.ReadByte() << 16
            | stream.ReadByte() << 8
            | stream.ReadByte());
    }

    public ulong ReadULong() {
        return (ulong)ReadUInt() << 32 | (ulong)ReadUInt();
    }

    public sbyte ReadSByte() {
        return (sbyte)ReadByte();
    }

    public short ReadShort() {
        return (short)ReadUShort();
    }

    public int ReadInt() {
        return (int)ReadUInt();
    }

    public float ReadFloat() {
        return BitConverter.Int32BitsToSingle(ReadInt());
    }

    public long ReadLong() {
        return (long)ReadULong();
    }

    public double ReadDouble() {
        return BitConverter.Int64BitsToDouble(ReadLong());
    }

    private void CheckRemaining(int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail which will be called internally by the public API.
static class _UniFFILib {
    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [DllImport("matrix_sdk_ffi")]
    public static extern void uniffi_matrix_sdk_ffi_fn_free_roommessageeventcontentwithoutrelation(
    IntPtr ptr,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RoomMessageEventContentWithoutRelationSafeHandle uniffi_matrix_sdk_ffi_fn_method_roommessageeventcontentwithoutrelation_with_mentions(RoomMessageEventContentWithoutRelationSafeHandle @ptr,RustBuffer @mentions,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern void uniffi_matrix_sdk_ffi_fn_free_mediasource(
    IntPtr ptr,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern MediaSourceSafeHandle uniffi_matrix_sdk_ffi_fn_constructor_mediasource_from_json(RustBuffer @json,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RustBuffer uniffi_matrix_sdk_ffi_fn_method_mediasource_to_json(MediaSourceSafeHandle @ptr,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RustBuffer uniffi_matrix_sdk_ffi_fn_method_mediasource_url(MediaSourceSafeHandle @ptr,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RustBuffer ffi_matrix_sdk_ffi_rustbuffer_alloc(int @size,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RustBuffer ffi_matrix_sdk_ffi_rustbuffer_from_bytes(ForeignBytes @bytes,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern void ffi_matrix_sdk_ffi_rustbuffer_free(RustBuffer @buf,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern RustBuffer ffi_matrix_sdk_ffi_rustbuffer_reserve(RustBuffer @buf,int @additional,ref RustCallStatus _uniffi_out_err
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern ushort uniffi_matrix_sdk_ffi_checksum_method_roommessageeventcontentwithoutrelation_with_mentions(
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern ushort uniffi_matrix_sdk_ffi_checksum_method_mediasource_to_json(
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern ushort uniffi_matrix_sdk_ffi_checksum_method_mediasource_url(
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern ushort uniffi_matrix_sdk_ffi_checksum_constructor_mediasource_from_json(
    );

    [DllImport("matrix_sdk_ffi")]
    public static extern uint ffi_matrix_sdk_ffi_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_matrix_sdk_ffi_uniffi_contract_version();
        if (22 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"Matrix.RustSdk.Bindings: uniffi bindings expected version `22`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_matrix_sdk_ffi_checksum_method_roommessageeventcontentwithoutrelation_with_mentions();
            if (checksum != 65407) {
                throw new UniffiContractChecksumException($"Matrix.RustSdk.Bindings: uniffi bindings expected function `uniffi_matrix_sdk_ffi_checksum_method_roommessageeventcontentwithoutrelation_with_mentions` checksum `65407`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_matrix_sdk_ffi_checksum_method_mediasource_to_json();
            if (checksum != 52259) {
                throw new UniffiContractChecksumException($"Matrix.RustSdk.Bindings: uniffi bindings expected function `uniffi_matrix_sdk_ffi_checksum_method_mediasource_to_json` checksum `52259`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_matrix_sdk_ffi_checksum_method_mediasource_url();
            if (checksum != 9248) {
                throw new UniffiContractChecksumException($"Matrix.RustSdk.Bindings: uniffi bindings expected function `uniffi_matrix_sdk_ffi_checksum_method_mediasource_url` checksum `9248`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_matrix_sdk_ffi_checksum_constructor_mediasource_from_json();
            if (checksum != 64601) {
                throw new UniffiContractChecksumException($"Matrix.RustSdk.Bindings: uniffi bindings expected function `uniffi_matrix_sdk_ffi_checksum_constructor_mediasource_from_json` checksum `64601`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(value.len);
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = value.Length * 3;
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}




// `SafeHandle` implements the semantics outlined below, i.e. its thread safe, and the dispose
// method will only be called once, once all outstanding native calls have completed.
// https://github.com/mozilla/uniffi-rs/blob/0dc031132d9493ca812c3af6e7dd60ad2ea95bf0/uniffi_bindgen/src/bindings/kotlin/templates/ObjectRuntime.kt#L31
// https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.criticalhandle

public abstract class FFIObject<THandle>: IDisposable where THandle : FFISafeHandle {
    private THandle handle;

    public FFIObject(THandle handle) {
        this.handle = handle;
    }

    public THandle GetHandle() {
        return handle;
    }

    public void Dispose() {
        handle.Dispose();
    }
}

public abstract class FFISafeHandle: SafeHandle {
    public FFISafeHandle(): base(new IntPtr(0), true) {
    }

    public FFISafeHandle(IntPtr pointer): this() {
        this.SetHandle(pointer);
    }

    public override bool IsInvalid {
        get {
            return handle.ToInt64() == 0;
        }
    }

    // TODO(CS) this completely breaks any guarantees offered by SafeHandle.. Extracting
    // raw value from SafeHandle puts responsiblity on the consumer of this function to
    // ensure that SafeHandle outlives the stream, and anyone who might have read the raw
    // value from the stream and are holding onto it. Otherwise, the result might be a use
    // after free, or free while method calls are still in flight.
    //
    // This is also relevant for Kotlin.
    //
    public IntPtr DangerousGetRawFfiValue() {
        return handle;
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        foreach (var obj in list) {
            Dispose(obj);
        }
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(dynamic? obj) {
        if (obj == null) {
            return;
        }

        if (obj is IDisposable disposable) {
            disposable.Dispose();
            return;
        }

        var type = obj.GetType();
        if (type != null) {
            if (type.IsGenericType) {
                if (type.GetGenericTypeDefinition().IsAssignableFrom(typeof(List<>))) {
                    foreach (var value in obj) {
                        Dispose(value);
                    }
                } else if (type.GetGenericTypeDefinition().IsAssignableFrom(typeof(Dictionary<,>))) {
                    foreach (var value in obj.Values) {
                        Dispose(value);
                    }
                }
            }
        }
    }
}
public interface IMediaSource {
    
    String ToJson();
    
    String Url();
    
}

public class MediaSourceSafeHandle: FFISafeHandle {
    public MediaSourceSafeHandle(): base() {
    }
    public MediaSourceSafeHandle(IntPtr pointer): base(pointer) {
    }
    override protected bool ReleaseHandle() {
        _UniffiHelpers.RustCall((ref RustCallStatus status) => {
            _UniFFILib.uniffi_matrix_sdk_ffi_fn_free_mediasource(this.handle, ref status);
        });
        return true;
    }
}
public class MediaSource: FFIObject<MediaSourceSafeHandle>, IMediaSource {
    public MediaSource(MediaSourceSafeHandle pointer): base(pointer) {}

    
    public String ToJson() {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref RustCallStatus _status) =>
    _UniFFILib.uniffi_matrix_sdk_ffi_fn_method_mediasource_to_json(this.GetHandle(),  ref _status)
));
    }
    
    public String Url() {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref RustCallStatus _status) =>
    _UniFFILib.uniffi_matrix_sdk_ffi_fn_method_mediasource_url(this.GetHandle(),  ref _status)
));
    }
    

    
    /// <exception cref="ClientException"></exception>
    public static MediaSource FromJson(String @json) {
        return new MediaSource(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientException.INSTANCE, (ref RustCallStatus _status) =>
    _UniFFILib.uniffi_matrix_sdk_ffi_fn_constructor_mediasource_from_json(FfiConverterString.INSTANCE.Lower(@json), ref _status)
));
    }
    
    
}

class FfiConverterTypeMediaSource: FfiConverter<MediaSource, MediaSourceSafeHandle> {
    public static FfiConverterTypeMediaSource INSTANCE = new FfiConverterTypeMediaSource();

    public override MediaSourceSafeHandle Lower(MediaSource value) {
        return value.GetHandle();
    }

    public override MediaSource Lift(MediaSourceSafeHandle value) {
        return new MediaSource(value);
    }

    public override MediaSource Read(BigEndianStream stream) {
        return Lift(new MediaSourceSafeHandle(new IntPtr(stream.ReadLong())));
    }

    public override int AllocationSize(MediaSource value) {
        return 8;
    }

    public override void Write(MediaSource value, BigEndianStream stream) {
        stream.WriteLong(Lower(value).DangerousGetRawFfiValue().ToInt64());
    }
}



public interface IRoomMessageEventContentWithoutRelation {
    
    RoomMessageEventContentWithoutRelation WithMentions(Mentions @mentions);
    
}

public class RoomMessageEventContentWithoutRelationSafeHandle: FFISafeHandle {
    public RoomMessageEventContentWithoutRelationSafeHandle(): base() {
    }
    public RoomMessageEventContentWithoutRelationSafeHandle(IntPtr pointer): base(pointer) {
    }
    override protected bool ReleaseHandle() {
        _UniffiHelpers.RustCall((ref RustCallStatus status) => {
            _UniFFILib.uniffi_matrix_sdk_ffi_fn_free_roommessageeventcontentwithoutrelation(this.handle, ref status);
        });
        return true;
    }
}
public class RoomMessageEventContentWithoutRelation: FFIObject<RoomMessageEventContentWithoutRelationSafeHandle>, IRoomMessageEventContentWithoutRelation {
    public RoomMessageEventContentWithoutRelation(RoomMessageEventContentWithoutRelationSafeHandle pointer): base(pointer) {}

    
    public RoomMessageEventContentWithoutRelation WithMentions(Mentions @mentions) {
        return FfiConverterTypeRoomMessageEventContentWithoutRelation.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref RustCallStatus _status) =>
    _UniFFILib.uniffi_matrix_sdk_ffi_fn_method_roommessageeventcontentwithoutrelation_with_mentions(this.GetHandle(), FfiConverterTypeMentions.INSTANCE.Lower(@mentions), ref _status)
));
    }
    

    
}

class FfiConverterTypeRoomMessageEventContentWithoutRelation: FfiConverter<RoomMessageEventContentWithoutRelation, RoomMessageEventContentWithoutRelationSafeHandle> {
    public static FfiConverterTypeRoomMessageEventContentWithoutRelation INSTANCE = new FfiConverterTypeRoomMessageEventContentWithoutRelation();

    public override RoomMessageEventContentWithoutRelationSafeHandle Lower(RoomMessageEventContentWithoutRelation value) {
        return value.GetHandle();
    }

    public override RoomMessageEventContentWithoutRelation Lift(RoomMessageEventContentWithoutRelationSafeHandle value) {
        return new RoomMessageEventContentWithoutRelation(value);
    }

    public override RoomMessageEventContentWithoutRelation Read(BigEndianStream stream) {
        return Lift(new RoomMessageEventContentWithoutRelationSafeHandle(new IntPtr(stream.ReadLong())));
    }

    public override int AllocationSize(RoomMessageEventContentWithoutRelation value) {
        return 8;
    }

    public override void Write(RoomMessageEventContentWithoutRelation value, BigEndianStream stream) {
        stream.WriteLong(Lower(value).DangerousGetRawFfiValue().ToInt64());
    }
}



public record Mentions (
    List<String> @userIds, 
    bool @room
) {
}

class FfiConverterTypeMentions: FfiConverterRustBuffer<Mentions> {
    public static FfiConverterTypeMentions INSTANCE = new FfiConverterTypeMentions();

    public override Mentions Read(BigEndianStream stream) {
        return new Mentions(
            FfiConverterSequenceString.INSTANCE.Read(stream),
            FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Mentions value) {
        return
            FfiConverterSequenceString.INSTANCE.AllocationSize(value.@userIds) +
            FfiConverterBoolean.INSTANCE.AllocationSize(value.@room);
    }

    public override void Write(Mentions value, BigEndianStream stream) {
            FfiConverterSequenceString.INSTANCE.Write(value.@userIds, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@room, stream);
    }
}





public enum BackPaginationStatus: int {
    
    Idle,
    Paginating,
    TimelineStartReached
}

class FfiConverterTypeBackPaginationStatus: FfiConverterRustBuffer<BackPaginationStatus> {
    public static FfiConverterTypeBackPaginationStatus INSTANCE = new FfiConverterTypeBackPaginationStatus();

    public override BackPaginationStatus Read(BigEndianStream stream) {
        var value = stream.ReadInt() - 1;
        if (Enum.IsDefined(typeof(BackPaginationStatus), value)) {
            return (BackPaginationStatus)value;
        } else {
            throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeBackPaginationStatus.Read()", value));
        }
    }

    public override int AllocationSize(BackPaginationStatus value) {
        return 4;
    }

    public override void Write(BackPaginationStatus value, BigEndianStream stream) {
        stream.WriteInt((int)value + 1);
    }
}







public class ClientException: UniffiException {
    // Each variant is a nested class
    
    
    public class Generic : ClientException {
        // Members
        public String @msg;

        // Constructor
        public Generic(
                String @msg) {
            this.@msg = @msg;
        }
    }
    

    
}

class FfiConverterTypeClientException : FfiConverterRustBuffer<ClientException>, CallStatusErrorHandler<ClientException> {
    public static FfiConverterTypeClientException INSTANCE = new FfiConverterTypeClientException();

    public override ClientException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new ClientException.Generic(
                    FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientException.Read()", value));
        }
    }

    public override int AllocationSize(ClientException value) {
        switch (value) {
            case ClientException.Generic variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@msg);
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientException.AllocationSize()", value));
        }
    }

    public override void Write(ClientException value, BigEndianStream stream) {
        switch (value) {
            case ClientException.Generic variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@msg, stream);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientException.Write()", value));
        }
    }
}





public enum EventItemOrigin: int {
    
    Local,
    Sync,
    Pagination
}

class FfiConverterTypeEventItemOrigin: FfiConverterRustBuffer<EventItemOrigin> {
    public static FfiConverterTypeEventItemOrigin INSTANCE = new FfiConverterTypeEventItemOrigin();

    public override EventItemOrigin Read(BigEndianStream stream) {
        var value = stream.ReadInt() - 1;
        if (Enum.IsDefined(typeof(EventItemOrigin), value)) {
            return (EventItemOrigin)value;
        } else {
            throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeEventItemOrigin.Read()", value));
        }
    }

    public override int AllocationSize(EventItemOrigin value) {
        return 4;
    }

    public override void Write(EventItemOrigin value, BigEndianStream stream) {
        stream.WriteInt((int)value + 1);
    }
}






class FfiConverterSequenceString: FfiConverterRustBuffer<List<String>> {
    public static FfiConverterSequenceString INSTANCE = new FfiConverterSequenceString();

    public override List<String> Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var result = new List<String>(length);
        for (int i = 0; i < length; i++) {
            result.Add(FfiConverterString.INSTANCE.Read(stream));
        }
        return result;
    }

    public override int AllocationSize(List<String> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var sizeForItems = value.Select(item => FfiConverterString.INSTANCE.AllocationSize(item)).Sum();
        return sizeForLength + sizeForItems;
    }

    public override void Write(List<String> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        value.ForEach(item => FfiConverterString.INSTANCE.Write(item, stream));
    }
}
#pragma warning restore 8625
public static class MatrixSdkFfiMethods {
}

