// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.12.0+v0.32.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Matrix.RustSdk.Bindings.RumaEvents;

namespace Matrix.RustSdk.Bindings.Ui;

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer
{
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size)
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                var buffer = _UniFFILib.ffi_matrix_sdk_ui_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
                if (buffer.data == IntPtr.Zero)
                {
                    throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
                }
                return buffer;
            }
        );
    }

    public static void Free(RustBuffer buffer)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.ffi_matrix_sdk_ui_rustbuffer_free(buffer, ref status);
            }
        );
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len)));
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// The pointer borrows foreign-owned memory, so it is only valid for the duration of
// the call it is passed to.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes
{
    public int length;
    public IntPtr data;
}

// Pins a `byte[]` so Rust can borrow it as `ForeignBytes` without copying. `[ByRef] bytes`
// (`&[u8]`) arguments take this zero-copy path instead of being copied into a `RustBuffer`.
// The array must stay pinned until the FFI call returns, so this is always used as a
// `using` declaration wrapping the call.
internal struct ForeignBytesPin : IDisposable
{
    private GCHandle _handle;
    private readonly int _length;

    public ForeignBytesPin(byte[] value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }
        _handle = GCHandle.Alloc(value, GCHandleType.Pinned);
        _length = value.Length;
    }

    public ForeignBytes Bytes
    {
        get { return new ForeignBytes { length = _length, data = _handle.AddrOfPinnedObject() }; }
    }

    public void Dispose()
    {
        if (_handle.IsAllocated)
        {
            _handle.Free();
        }
    }
}

// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType>
{
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value)
    {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try
        {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        }
        catch
        {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf)
    {
        var stream = rbuf.AsStream();
        try
        {
            var item = Read(stream);
            if (stream.HasRemaining())
            {
                throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
            }
            return item;
        }
        finally
        {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType> : FfiConverter<CsType, RustBuffer>
{
    public override CsType Lift(RustBuffer value)
    {
        return LiftFromRustBuffer(value);
    }

    public override RustBuffer Lower(CsType value)
    {
        return LowerIntoRustBuffer(value);
    }
}

// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus
{
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess()
    {
        return code == 0;
    }

    public bool IsError()
    {
        return code == 1;
    }

    public bool IsPanic()
    {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException : System.Exception
{
    public UniffiException()
        : base() { }

    public UniffiException(string message)
        : base(message) { }
}

public class UndeclaredErrorException : UniffiException
{
    public UndeclaredErrorException(string message)
        : base(message) { }
}

public class PanicException : UniffiException
{
    public PanicException(string message)
        : base(message) { }
}

public class AllocationException : UniffiException
{
    public AllocationException(string message)
        : base(message) { }
}

public class InternalException : UniffiException
{
    public InternalException(string message)
        : base(message) { }
}

public class InvalidEnumException : InternalException
{
    public InvalidEnumException(string message)
        : base(message) { }
}

public class UniffiContractVersionException : UniffiException
{
    public UniffiContractVersionException(string message)
        : base(message) { }
}

public class UniffiContractChecksumException : UniffiException
{
    public UniffiContractChecksumException(string message)
        : base(message) { }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E>
    where E : System.Exception
{
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler : CallStatusErrorHandler<UniffiException>
{
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf)
    {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers
{
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E : System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess())
        {
            return return_value;
        }
        else if (status.IsError())
        {
            throw errorHandler.Lift(status.error_buf);
        }
        else if (status.IsPanic())
        {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0)
            {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            }
            else
            {
                throw new PanicException("Rust panic");
            }
        }
        else
        {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E : System.Exception
    {
        _UniffiHelpers.RustCallWithError(
            errorHandler,
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback)
    {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }
}

static class FFIObjectUtil
{
    public static void DisposeAll(params Object?[] list)
    {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(Object? obj)
    {
        if (obj == null)
        {
            return;
        }

        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        var objType = obj.GetType();
        var typeCode = Type.GetTypeCode(objType);
        if (typeCode != TypeCode.Object)
        {
            return;
        }

        var genericArguments = objType.GetGenericArguments();
        if (genericArguments.Length == 0 && !objType.IsArray)
        {
            return;
        }

        if (obj is System.Collections.IDictionary objDictionary)
        {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all values as "double" and alike doesn't support interface "IDisposable"
            var valuesType = objType.GetGenericArguments()[1];
            var elementValuesTypeCode = Type.GetTypeCode(valuesType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in objDictionary.Values)
            {
                Dispose(value);
            }
        }
        else if (obj is System.Collections.IEnumerable listValues)
        {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
            var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
            var elementValuesTypeCode = Type.GetTypeCode(elementType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in listValues)
            {
                Dispose(value);
            }
        }
    }
}

// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException : System.Exception
{
    public StreamUnderflowException() { }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4)
    {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream)
    {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length)
    {
        if (stream.Length - stream.Position < length)
        {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action)
    {
        foreach (var item in items)
        {
            action(item);
        }
    }
}

class BigEndianStream
{
    Stream stream;

    public BigEndianStream(Stream stream)
    {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining()
    {
        return (stream.Length - Position) > 0;
    }

    public long Position
    {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer)
    {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);

    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);

    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value)
    {
        unsafe
        {
            WriteInt(*((int*)&value));
        }
    }

    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length)
    {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);

    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);

    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);

    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();

    public short ReadShort() => (short)ReadUShort();

    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat()
    {
        unsafe
        {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();

    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.

// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib
{
#else
static class _UniFFILib
{
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(ulong @data, sbyte @pollResult);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(ulong @handle);

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultVoid @result
    );

    static _UniFFILib()
    {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
    }

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_ui_rustbuffer_alloc(ulong @size, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_ui_rustbuffer_from_bytes(ForeignBytes @bytes, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rustbuffer_free(RustBuffer @buf, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_ui_rustbuffer_reserve(
        RustBuffer @buf,
        ulong @additional,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_u8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    byte ffi_matrix_sdk_ui_rust_future_complete_u8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_i8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    sbyte ffi_matrix_sdk_ui_rust_future_complete_i8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_u16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ushort ffi_matrix_sdk_ui_rust_future_complete_u16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_i16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    short ffi_matrix_sdk_ui_rust_future_complete_i16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_u32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_ui_rust_future_complete_u32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_i32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    int ffi_matrix_sdk_ui_rust_future_complete_i32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_u64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong ffi_matrix_sdk_ui_rust_future_complete_u64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_i64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    long ffi_matrix_sdk_ui_rust_future_complete_i64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_f32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    float ffi_matrix_sdk_ui_rust_future_complete_f32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_f64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    double ffi_matrix_sdk_ui_rust_future_complete_f64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_rust_buffer(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_ui_rust_future_complete_rust_buffer(
        ulong @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_poll_void(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_cancel_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_free_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_ui_rust_future_complete_void(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_ui_uniffi_contract_version();

    static void uniffiCheckContractApiVersion()
    {
        var scaffolding_contract_version = _UniFFILib.ffi_matrix_sdk_ui_uniffi_contract_version();
        if (30 != scaffolding_contract_version)
        {
            throw new UniffiContractVersionException(
                $"Matrix.RustSdk.Bindings.Ui: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`"
            );
        }
    }

    static void uniffiCheckApiChecksums() { }
}

// Public interface members begin here.

#pragma warning disable 8625

class FfiConverterBoolean : FfiConverter<bool, sbyte>
{
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value)
    {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream)
    {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value)
    {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value)
    {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream)
    {
        stream.WriteSByte(Lower(value));
    }
}

class FfiConverterString : FfiConverter<string, RustBuffer>
{
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value)
    {
        try
        {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        }
        finally
        {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value)
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value)
    {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream)
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}

/// <summary>
/// Where this event came.
/// </summary>
public enum EventItemOrigin : int
{
    /// <summary>
    /// The event was created locally.
    /// </summary>
    Local,

    /// <summary>
    /// The event came from a sync response.
    /// </summary>
    Sync,

    /// <summary>
    /// The event came from pagination.
    /// </summary>
    Pagination,

    /// <summary>
    /// The event came from a cache.
    /// </summary>
    Cache,
}

class FfiConverterTypeEventItemOrigin : FfiConverterRustBuffer<EventItemOrigin>
{
    public static FfiConverterTypeEventItemOrigin INSTANCE = new FfiConverterTypeEventItemOrigin();

    public override EventItemOrigin Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return EventItemOrigin.Local;
            case 2:
                return EventItemOrigin.Sync;
            case 3:
                return EventItemOrigin.Pagination;
            case 4:
                return EventItemOrigin.Cache;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeEventItemOrigin.Read()", value)
                );
        }
    }

    public override int AllocationSize(EventItemOrigin value)
    {
        return 4;
    }

    public override void Write(EventItemOrigin value, BigEndianStream stream)
    {
        switch (value)
        {
            case EventItemOrigin.Local:
                stream.WriteInt(1);
                break;
            case EventItemOrigin.Sync:
                stream.WriteInt(2);
                break;
            case EventItemOrigin.Pagination:
                stream.WriteInt(3);
                break;
            case EventItemOrigin.Cache:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeEventItemOrigin.Write()", value)
                );
        }
    }
}

public enum LatestEventValueLocalState : int
{
    IsSending,
    HasBeenSent,
    CannotBeSent,
}

class FfiConverterTypeLatestEventValueLocalState : FfiConverterRustBuffer<LatestEventValueLocalState>
{
    public static FfiConverterTypeLatestEventValueLocalState INSTANCE =
        new FfiConverterTypeLatestEventValueLocalState();

    public override LatestEventValueLocalState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return LatestEventValueLocalState.IsSending;
            case 2:
                return LatestEventValueLocalState.HasBeenSent;
            case 3:
                return LatestEventValueLocalState.CannotBeSent;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeLatestEventValueLocalState.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(LatestEventValueLocalState value)
    {
        return 4;
    }

    public override void Write(LatestEventValueLocalState value, BigEndianStream stream)
    {
        switch (value)
        {
            case LatestEventValueLocalState.IsSending:
                stream.WriteInt(1);
                break;
            case LatestEventValueLocalState.HasBeenSent:
                stream.WriteInt(2);
                break;
            case LatestEventValueLocalState.CannotBeSent:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeLatestEventValueLocalState.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// The membership states that should be included/excluded from the timeline
/// item filters.
/// </summary>
public enum MembershipChangeFilter : int
{
    /// <summary>
    /// Include/exclude all membership state events.
    /// </summary>
    Any,

    /// <summary>
    /// Include/exclude only `join` membership state events.
    /// </summary>
    Join,

    /// <summary>
    /// Include/exclude only `leave` membership state events.
    /// </summary>
    Leave,

    /// <summary>
    /// Include/exclude only `invite` membership state events.
    /// </summary>
    Invite,

    /// <summary>
    /// Include/exclude only `ban` membership state events.
    /// </summary>
    Ban,

    /// <summary>
    /// Include/exclude only `knock` membership state events.
    /// </summary>
    Knock,
}

class FfiConverterTypeMembershipChangeFilter : FfiConverterRustBuffer<MembershipChangeFilter>
{
    public static FfiConverterTypeMembershipChangeFilter INSTANCE = new FfiConverterTypeMembershipChangeFilter();

    public override MembershipChangeFilter Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return MembershipChangeFilter.Any;
            case 2:
                return MembershipChangeFilter.Join;
            case 3:
                return MembershipChangeFilter.Leave;
            case 4:
                return MembershipChangeFilter.Invite;
            case 5:
                return MembershipChangeFilter.Ban;
            case 6:
                return MembershipChangeFilter.Knock;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeMembershipChangeFilter.Read()", value)
                );
        }
    }

    public override int AllocationSize(MembershipChangeFilter value)
    {
        return 4;
    }

    public override void Write(MembershipChangeFilter value, BigEndianStream stream)
    {
        switch (value)
        {
            case MembershipChangeFilter.Any:
                stream.WriteInt(1);
                break;
            case MembershipChangeFilter.Join:
                stream.WriteInt(2);
                break;
            case MembershipChangeFilter.Leave:
                stream.WriteInt(3);
                break;
            case MembershipChangeFilter.Invite:
                stream.WriteInt(4);
                break;
            case MembershipChangeFilter.Ban:
                stream.WriteInt(5);
                break;
            case MembershipChangeFilter.Knock:
                stream.WriteInt(6);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeMembershipChangeFilter.Write()", value)
                );
        }
    }
}

/// <summary>
/// An enum to represent whether a room is about “people” (strictly 2 users) or
/// “group” (1 or more than 2 users).
///
/// Ideally, we would only want to rely on the
/// [`matrix_sdk::BaseRoom::is_direct`] method, but the rules are a little bit
/// different for this high-level UI API.
///
/// This is implemented this way so that it's impossible to filter by “group”
/// and by “people” at the same time: these criteria are mutually
/// exclusive by design per filter.
/// </summary>
public enum RoomListFilterCategory : int
{
    Group,
    People,
}

class FfiConverterTypeRoomListFilterCategory : FfiConverterRustBuffer<RoomListFilterCategory>
{
    public static FfiConverterTypeRoomListFilterCategory INSTANCE = new FfiConverterTypeRoomListFilterCategory();

    public override RoomListFilterCategory Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return RoomListFilterCategory.Group;
            case 2:
                return RoomListFilterCategory.People;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeRoomListFilterCategory.Read()", value)
                );
        }
    }

    public override int AllocationSize(RoomListFilterCategory value)
    {
        return 4;
    }

    public override void Write(RoomListFilterCategory value, BigEndianStream stream)
    {
        switch (value)
        {
            case RoomListFilterCategory.Group:
                stream.WriteInt(1);
                break;
            case RoomListFilterCategory.People:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeRoomListFilterCategory.Write()", value)
                );
        }
    }
}

/// <summary>
/// Filter read receipts by…
///
/// This type decides which fields to reach in [`ReadReceipts`].
///
/// [`ReadReceipts`]: matrix_sdk_base::read_receipts::ReadReceipts
/// </summary>
public enum RoomListFilterReadReceipts : int
{
    /// <summary>
    /// Filter by mentions, i.e. [`ReadReceipts::num_mentions`].
    ///
    /// [`ReadReceipts::num_mentions`]: matrix_sdk_base::read_receipts::ReadReceipts::num_mentions
    /// </summary>
    Mentions,

    /// <summary>
    /// Filter by notifications, i.e. [`ReadReceipts::num_notifications`].
    ///
    /// [`ReadReceipts::num_notifications`]: matrix_sdk_base::read_receipts::ReadReceipts::num_notifications
    /// </summary>
    Notifications,

    /// <summary>
    /// Filter by messages, i.e. [`ReadReceipts::num_unread`].
    ///
    /// [`ReadReceipts::num_unread`]: matrix_sdk_base::read_receipts::ReadReceipts::num_unread
    /// </summary>
    Messages,
}

class FfiConverterTypeRoomListFilterReadReceipts : FfiConverterRustBuffer<RoomListFilterReadReceipts>
{
    public static FfiConverterTypeRoomListFilterReadReceipts INSTANCE =
        new FfiConverterTypeRoomListFilterReadReceipts();

    public override RoomListFilterReadReceipts Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return RoomListFilterReadReceipts.Mentions;
            case 2:
                return RoomListFilterReadReceipts.Notifications;
            case 3:
                return RoomListFilterReadReceipts.Messages;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeRoomListFilterReadReceipts.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(RoomListFilterReadReceipts value)
    {
        return 4;
    }

    public override void Write(RoomListFilterReadReceipts value, BigEndianStream stream)
    {
        switch (value)
        {
            case RoomListFilterReadReceipts.Mentions:
                stream.WriteInt(1);
                break;
            case RoomListFilterReadReceipts.Notifications:
                stream.WriteInt(2);
                break;
            case RoomListFilterReadReceipts.Messages:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeRoomListFilterReadReceipts.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// The type of change between the previous and current pinned events.
/// </summary>
public enum RoomPinnedEventsChange : int
{
    /// <summary>
    /// Only new event ids were added.
    /// </summary>
    Added,

    /// <summary>
    /// Only event ids were removed.
    /// </summary>
    Removed,

    /// <summary>
    /// Some change other than only adding or only removing ids happened.
    /// </summary>
    Changed,
}

class FfiConverterTypeRoomPinnedEventsChange : FfiConverterRustBuffer<RoomPinnedEventsChange>
{
    public static FfiConverterTypeRoomPinnedEventsChange INSTANCE = new FfiConverterTypeRoomPinnedEventsChange();

    public override RoomPinnedEventsChange Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return RoomPinnedEventsChange.Added;
            case 2:
                return RoomPinnedEventsChange.Removed;
            case 3:
                return RoomPinnedEventsChange.Changed;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeRoomPinnedEventsChange.Read()", value)
                );
        }
    }

    public override int AllocationSize(RoomPinnedEventsChange value)
    {
        return 4;
    }

    public override void Write(RoomPinnedEventsChange value, BigEndianStream stream)
    {
        switch (value)
        {
            case RoomPinnedEventsChange.Added:
                stream.WriteInt(1);
                break;
            case RoomPinnedEventsChange.Removed:
                stream.WriteInt(2);
                break;
            case RoomPinnedEventsChange.Changed:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeRoomPinnedEventsChange.Write()", value)
                );
        }
    }
}

/// <summary>
/// Whether the search service is currently loading a page of results.
/// </summary>
public record SearchServicePaginationState
{
    /// <summary>
    /// Not currently paginating. `end_reached` is `true` once every source has
    /// been exhausted for the current query.
    /// </summary>
    public record Idle(bool EndReached) : SearchServicePaginationState { }

    /// <summary>
    /// A page of results is currently being loaded.
    /// </summary>
    public record Loading : SearchServicePaginationState { }
}

class FfiConverterTypeSearchServicePaginationState : FfiConverterRustBuffer<SearchServicePaginationState>
{
    public static FfiConverterRustBuffer<SearchServicePaginationState> INSTANCE =
        new FfiConverterTypeSearchServicePaginationState();

    public override SearchServicePaginationState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new SearchServicePaginationState.Idle(FfiConverterBoolean.INSTANCE.Read(stream));
            case 2:
                return new SearchServicePaginationState.Loading();
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSearchServicePaginationState.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(SearchServicePaginationState value)
    {
        switch (value)
        {
            case SearchServicePaginationState.Idle variant_value:
                return 4 + FfiConverterBoolean.INSTANCE.AllocationSize(variant_value.EndReached);
            case SearchServicePaginationState.Loading variant_value:
                return 4;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSearchServicePaginationState.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(SearchServicePaginationState value, BigEndianStream stream)
    {
        switch (value)
        {
            case SearchServicePaginationState.Idle variant_value:
                stream.WriteInt(1);
                FfiConverterBoolean.INSTANCE.Write(variant_value.EndReached, stream);
                break;
            case SearchServicePaginationState.Loading variant_value:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSearchServicePaginationState.Write()",
                        value
                    )
                );
        }
    }
}

public record SpaceRoomListPaginationState
{
    public record Idle(bool EndReached) : SpaceRoomListPaginationState { }

    public record Loading : SpaceRoomListPaginationState { }
}

class FfiConverterTypeSpaceRoomListPaginationState : FfiConverterRustBuffer<SpaceRoomListPaginationState>
{
    public static FfiConverterRustBuffer<SpaceRoomListPaginationState> INSTANCE =
        new FfiConverterTypeSpaceRoomListPaginationState();

    public override SpaceRoomListPaginationState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new SpaceRoomListPaginationState.Idle(FfiConverterBoolean.INSTANCE.Read(stream));
            case 2:
                return new SpaceRoomListPaginationState.Loading();
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSpaceRoomListPaginationState.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(SpaceRoomListPaginationState value)
    {
        switch (value)
        {
            case SpaceRoomListPaginationState.Idle variant_value:
                return 4 + FfiConverterBoolean.INSTANCE.AllocationSize(variant_value.EndReached);
            case SpaceRoomListPaginationState.Loading variant_value:
                return 4;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSpaceRoomListPaginationState.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(SpaceRoomListPaginationState value, BigEndianStream stream)
    {
        switch (value)
        {
            case SpaceRoomListPaginationState.Idle variant_value:
                stream.WriteInt(1);
                FfiConverterBoolean.INSTANCE.Write(variant_value.EndReached, stream);
                break;
            case SpaceRoomListPaginationState.Loading variant_value:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeSpaceRoomListPaginationState.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// The pagination state of a [`ThreadListService`].
/// </summary>
public record ThreadListPaginationState
{
    /// <summary>
    /// The list is idle (not currently loading).
    /// </summary>
    public record Idle(bool EndReached) : ThreadListPaginationState { }

    /// <summary>
    /// The list is currently loading the next page.
    /// </summary>
    public record Loading : ThreadListPaginationState { }
}

class FfiConverterTypeThreadListPaginationState : FfiConverterRustBuffer<ThreadListPaginationState>
{
    public static FfiConverterRustBuffer<ThreadListPaginationState> INSTANCE =
        new FfiConverterTypeThreadListPaginationState();

    public override ThreadListPaginationState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new ThreadListPaginationState.Idle(FfiConverterBoolean.INSTANCE.Read(stream));
            case 2:
                return new ThreadListPaginationState.Loading();
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeThreadListPaginationState.Read()", value)
                );
        }
    }

    public override int AllocationSize(ThreadListPaginationState value)
    {
        switch (value)
        {
            case ThreadListPaginationState.Idle variant_value:
                return 4 + FfiConverterBoolean.INSTANCE.AllocationSize(variant_value.EndReached);
            case ThreadListPaginationState.Loading variant_value:
                return 4;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeThreadListPaginationState.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(ThreadListPaginationState value, BigEndianStream stream)
    {
        switch (value)
        {
            case ThreadListPaginationState.Idle variant_value:
                stream.WriteInt(1);
                FfiConverterBoolean.INSTANCE.Write(variant_value.EndReached, stream);
                break;
            case ThreadListPaginationState.Loading variant_value:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeThreadListPaginationState.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// A condition that matches on an event's type or content.
/// </summary>
public record TimelineEventCondition
{
    /// <summary>
    /// The event has the specified event type.
    /// </summary>
    public record EventType(TimelineEventType V1) : TimelineEventCondition { }

    /// <summary>
    /// The event is an `m.room.member` event that represents a membership
    /// change (join, leave, etc.).
    /// </summary>
    public record MembershipChange(MembershipChangeFilter V1) : TimelineEventCondition { }

    /// <summary>
    /// The event is an `m.room.member` event that represents a profile
    /// change (displayname or avatar URL).
    /// </summary>
    public record ProfileChange : TimelineEventCondition { }

    /// <summary>
    /// The event is a custom message-like event type.
    /// </summary>
    public record AnyCustomMessageLikeEvent : TimelineEventCondition { }

    /// <summary>
    /// The event is a custom state event type.
    /// </summary>
    public record AnyCustomStateEvent : TimelineEventCondition { }
}

class FfiConverterTypeTimelineEventCondition : FfiConverterRustBuffer<TimelineEventCondition>
{
    public static FfiConverterRustBuffer<TimelineEventCondition> INSTANCE =
        new FfiConverterTypeTimelineEventCondition();

    public override TimelineEventCondition Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new TimelineEventCondition.EventType(FfiConverterTypeTimelineEventType.INSTANCE.Read(stream));
            case 2:
                return new TimelineEventCondition.MembershipChange(
                    FfiConverterTypeMembershipChangeFilter.INSTANCE.Read(stream)
                );
            case 3:
                return new TimelineEventCondition.ProfileChange();
            case 4:
                return new TimelineEventCondition.AnyCustomMessageLikeEvent();
            case 5:
                return new TimelineEventCondition.AnyCustomStateEvent();
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTimelineEventCondition.Read()", value)
                );
        }
    }

    public override int AllocationSize(TimelineEventCondition value)
    {
        switch (value)
        {
            case TimelineEventCondition.EventType variant_value:
                return 4 + FfiConverterTypeTimelineEventType.INSTANCE.AllocationSize(variant_value.V1);
            case TimelineEventCondition.MembershipChange variant_value:
                return 4 + FfiConverterTypeMembershipChangeFilter.INSTANCE.AllocationSize(variant_value.V1);
            case TimelineEventCondition.ProfileChange variant_value:
                return 4;
            case TimelineEventCondition.AnyCustomMessageLikeEvent variant_value:
                return 4;
            case TimelineEventCondition.AnyCustomStateEvent variant_value:
                return 4;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventCondition.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(TimelineEventCondition value, BigEndianStream stream)
    {
        switch (value)
        {
            case TimelineEventCondition.EventType variant_value:
                stream.WriteInt(1);
                FfiConverterTypeTimelineEventType.INSTANCE.Write(variant_value.V1, stream);
                break;
            case TimelineEventCondition.MembershipChange variant_value:
                stream.WriteInt(2);
                FfiConverterTypeMembershipChangeFilter.INSTANCE.Write(variant_value.V1, stream);
                break;
            case TimelineEventCondition.ProfileChange variant_value:
                stream.WriteInt(3);
                break;
            case TimelineEventCondition.AnyCustomMessageLikeEvent variant_value:
                stream.WriteInt(4);
                break;
            case TimelineEventCondition.AnyCustomStateEvent variant_value:
                stream.WriteInt(5);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTimelineEventCondition.Write()", value)
                );
        }
    }
}

/// <summary>
/// A timeline filter that in- or excludes events based on their type or
/// content.
/// </summary>
public record TimelineEventFilter
{
    /// <summary>
    /// Only return items whose event matches any of the conditions in the list.
    /// </summary>
    public record Include(TimelineEventCondition[] V1) : TimelineEventFilter { }

    /// <summary>
    /// Return all items except the ones whose event matches any of the
    /// conditions in the list
    /// </summary>
    public record Exclude(TimelineEventCondition[] V1) : TimelineEventFilter { }
}

class FfiConverterTypeTimelineEventFilter : FfiConverterRustBuffer<TimelineEventFilter>
{
    public static FfiConverterRustBuffer<TimelineEventFilter> INSTANCE = new FfiConverterTypeTimelineEventFilter();

    public override TimelineEventFilter Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new TimelineEventFilter.Include(
                    FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.Read(stream)
                );
            case 2:
                return new TimelineEventFilter.Exclude(
                    FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.Read(stream)
                );
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTimelineEventFilter.Read()", value)
                );
        }
    }

    public override int AllocationSize(TimelineEventFilter value)
    {
        switch (value)
        {
            case TimelineEventFilter.Include variant_value:
                return 4 + FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.AllocationSize(variant_value.V1);
            case TimelineEventFilter.Exclude variant_value:
                return 4 + FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.AllocationSize(variant_value.V1);
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventFilter.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(TimelineEventFilter value, BigEndianStream stream)
    {
        switch (value)
        {
            case TimelineEventFilter.Include variant_value:
                stream.WriteInt(1);
                FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.Write(variant_value.V1, stream);
                break;
            case TimelineEventFilter.Exclude variant_value:
                stream.WriteInt(2);
                FfiConverterSequenceTypeTimelineEventCondition.INSTANCE.Write(variant_value.V1, stream);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTimelineEventFilter.Write()", value)
                );
        }
    }
}

/// <summary>
/// Options for controlling the behaviour of [`TimelineFocus::Event`]
/// for threaded events.
/// </summary>
public record TimelineEventFocusThreadMode
{
    /// <summary>
    /// Force the timeline into threaded mode.
    ///
    /// When the focused event is part of a thread, the timeline will be focused
    /// on that thread's root. Otherwise, the timeline will treat the target
    /// event itself as the thread root. Threaded events will never be
    /// hidden.
    /// </summary>
    public record ForceThread : TimelineEventFocusThreadMode { }

    /// <summary>
    /// Automatically determine if the target event is part of a thread or not.
    ///
    /// If the event is part of a thread, the timeline
    /// will be filtered to on-thread events.
    /// </summary>
    public record Automatic(bool HideThreadedEvents) : TimelineEventFocusThreadMode { }
}

class FfiConverterTypeTimelineEventFocusThreadMode : FfiConverterRustBuffer<TimelineEventFocusThreadMode>
{
    public static FfiConverterRustBuffer<TimelineEventFocusThreadMode> INSTANCE =
        new FfiConverterTypeTimelineEventFocusThreadMode();

    public override TimelineEventFocusThreadMode Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new TimelineEventFocusThreadMode.ForceThread();
            case 2:
                return new TimelineEventFocusThreadMode.Automatic(FfiConverterBoolean.INSTANCE.Read(stream));
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventFocusThreadMode.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(TimelineEventFocusThreadMode value)
    {
        switch (value)
        {
            case TimelineEventFocusThreadMode.ForceThread variant_value:
                return 4;
            case TimelineEventFocusThreadMode.Automatic variant_value:
                return 4 + FfiConverterBoolean.INSTANCE.AllocationSize(variant_value.HideThreadedEvents);
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventFocusThreadMode.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(TimelineEventFocusThreadMode value, BigEndianStream stream)
    {
        switch (value)
        {
            case TimelineEventFocusThreadMode.ForceThread variant_value:
                stream.WriteInt(1);
                break;
            case TimelineEventFocusThreadMode.Automatic variant_value:
                stream.WriteInt(2);
                FfiConverterBoolean.INSTANCE.Write(variant_value.HideThreadedEvents, stream);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventFocusThreadMode.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// Extends [`ShieldStateCode`] to allow for a `SentInClear` code.
/// </summary>
public enum TimelineEventShieldStateCode : int
{
    /// <summary>
    /// Not enough information available to check the authenticity.
    /// </summary>
    AuthenticityNotGuaranteed,

    /// <summary>
    /// The sending device isn't yet known by the Client.
    /// </summary>
    UnknownDevice,

    /// <summary>
    /// The sending device hasn't been verified by the sender.
    /// </summary>
    UnsignedDevice,

    /// <summary>
    /// The sender hasn't been verified by the Client's user.
    /// </summary>
    UnverifiedIdentity,

    /// <summary>
    /// The sender was previously verified but changed their identity.
    /// </summary>
    VerificationViolation,

    /// <summary>
    /// The `sender` field on the event does not match the owner of the device
    /// that established the Megolm session.
    /// </summary>
    MismatchedSender,

    /// <summary>
    /// An unencrypted event in an encrypted room.
    /// </summary>
    SentInClear,
}

class FfiConverterTypeTimelineEventShieldStateCode : FfiConverterRustBuffer<TimelineEventShieldStateCode>
{
    public static FfiConverterTypeTimelineEventShieldStateCode INSTANCE =
        new FfiConverterTypeTimelineEventShieldStateCode();

    public override TimelineEventShieldStateCode Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return TimelineEventShieldStateCode.AuthenticityNotGuaranteed;
            case 2:
                return TimelineEventShieldStateCode.UnknownDevice;
            case 3:
                return TimelineEventShieldStateCode.UnsignedDevice;
            case 4:
                return TimelineEventShieldStateCode.UnverifiedIdentity;
            case 5:
                return TimelineEventShieldStateCode.VerificationViolation;
            case 6:
                return TimelineEventShieldStateCode.MismatchedSender;
            case 7:
                return TimelineEventShieldStateCode.SentInClear;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventShieldStateCode.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(TimelineEventShieldStateCode value)
    {
        return 4;
    }

    public override void Write(TimelineEventShieldStateCode value, BigEndianStream stream)
    {
        switch (value)
        {
            case TimelineEventShieldStateCode.AuthenticityNotGuaranteed:
                stream.WriteInt(1);
                break;
            case TimelineEventShieldStateCode.UnknownDevice:
                stream.WriteInt(2);
                break;
            case TimelineEventShieldStateCode.UnsignedDevice:
                stream.WriteInt(3);
                break;
            case TimelineEventShieldStateCode.UnverifiedIdentity:
                stream.WriteInt(4);
                break;
            case TimelineEventShieldStateCode.VerificationViolation:
                stream.WriteInt(5);
                break;
            case TimelineEventShieldStateCode.MismatchedSender:
                stream.WriteInt(6);
                break;
            case TimelineEventShieldStateCode.SentInClear:
                stream.WriteInt(7);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineEventShieldStateCode.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// The level of read receipt tracking for the timeline.
/// </summary>
public enum TimelineReadReceiptTracking : int
{
    /// <summary>
    /// Track read receipts for all events.
    /// </summary>
    AllEvents,

    /// <summary>
    /// Track read receipts only for message-like events.
    /// </summary>
    MessageLikeEvents,

    /// <summary>
    /// Disable read receipt tracking.
    /// </summary>
    Disabled,
}

class FfiConverterTypeTimelineReadReceiptTracking : FfiConverterRustBuffer<TimelineReadReceiptTracking>
{
    public static FfiConverterTypeTimelineReadReceiptTracking INSTANCE =
        new FfiConverterTypeTimelineReadReceiptTracking();

    public override TimelineReadReceiptTracking Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return TimelineReadReceiptTracking.AllEvents;
            case 2:
                return TimelineReadReceiptTracking.MessageLikeEvents;
            case 3:
                return TimelineReadReceiptTracking.Disabled;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineReadReceiptTracking.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(TimelineReadReceiptTracking value)
    {
        return 4;
    }

    public override void Write(TimelineReadReceiptTracking value, BigEndianStream stream)
    {
        switch (value)
        {
            case TimelineReadReceiptTracking.AllEvents:
                stream.WriteInt(1);
                break;
            case TimelineReadReceiptTracking.MessageLikeEvents:
                stream.WriteInt(2);
                break;
            case TimelineReadReceiptTracking.Disabled:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeTimelineReadReceiptTracking.Write()",
                        value
                    )
                );
        }
    }
}

class FfiConverterSequenceTypeTimelineEventCondition : FfiConverterRustBuffer<TimelineEventCondition[]>
{
    public static FfiConverterSequenceTypeTimelineEventCondition INSTANCE =
        new FfiConverterSequenceTypeTimelineEventCondition();

    public override TimelineEventCondition[] Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        if (length == 0)
        {
            return [];
        }

        var result = new TimelineEventCondition[length];
        var readFn = FfiConverterTypeTimelineEventCondition.INSTANCE.Read;
        for (int i = 0; i < length; i++)
        {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(TimelineEventCondition[] value)
    {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeTimelineEventCondition.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(TimelineEventCondition[] value, BigEndianStream stream)
    {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null)
        {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeTimelineEventCondition.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}

class FfiConverterTypeTimelineEventType : FfiConverterRustBuffer<TimelineEventType>
{
    public static FfiConverterTypeTimelineEventType INSTANCE = new FfiConverterTypeTimelineEventType();

    public override TimelineEventType Read(BigEndianStream stream)
    {
        return Matrix.RustSdk.Bindings.RumaEvents.FfiConverterTypeTimelineEventType.INSTANCE.Read(
            new Matrix.RustSdk.Bindings.RumaEvents.BigEndianStream(stream.InnerStream)
        );
    }

    public override int AllocationSize(TimelineEventType value)
    {
        return Matrix.RustSdk.Bindings.RumaEvents.FfiConverterTypeTimelineEventType.INSTANCE.AllocationSize(value);
    }

    public override void Write(TimelineEventType value, BigEndianStream stream)
    {
        Matrix.RustSdk.Bindings.RumaEvents.FfiConverterTypeTimelineEventType.INSTANCE.Write(
            value,
            new Matrix.RustSdk.Bindings.RumaEvents.BigEndianStream(stream.InnerStream)
        );
    }
}
#pragma warning restore 8625
public static class MatrixSdkUiMethods { }
