// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.11.1+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Matrix.RustSdk.Bindings.Common;

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer
{
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size)
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                var buffer = _UniFFILib.ffi_matrix_sdk_common_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
                if (buffer.data == IntPtr.Zero)
                {
                    throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
                }
                return buffer;
            }
        );
    }

    public static void Free(RustBuffer buffer)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.ffi_matrix_sdk_common_rustbuffer_free(buffer, ref status);
            }
        );
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len)));
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes
{
    public int length;
    public IntPtr data;
}

// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType>
{
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value)
    {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try
        {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        }
        catch
        {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf)
    {
        var stream = rbuf.AsStream();
        try
        {
            var item = Read(stream);
            if (stream.HasRemaining())
            {
                throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
            }
            return item;
        }
        finally
        {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType> : FfiConverter<CsType, RustBuffer>
{
    public override CsType Lift(RustBuffer value)
    {
        return LiftFromRustBuffer(value);
    }

    public override RustBuffer Lower(CsType value)
    {
        return LowerIntoRustBuffer(value);
    }
}

// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus
{
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess()
    {
        return code == 0;
    }

    public bool IsError()
    {
        return code == 1;
    }

    public bool IsPanic()
    {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException : System.Exception
{
    public UniffiException()
        : base() { }

    public UniffiException(string message)
        : base(message) { }
}

public class UndeclaredErrorException : UniffiException
{
    public UndeclaredErrorException(string message)
        : base(message) { }
}

public class PanicException : UniffiException
{
    public PanicException(string message)
        : base(message) { }
}

public class AllocationException : UniffiException
{
    public AllocationException(string message)
        : base(message) { }
}

public class InternalException : UniffiException
{
    public InternalException(string message)
        : base(message) { }
}

public class InvalidEnumException : InternalException
{
    public InvalidEnumException(string message)
        : base(message) { }
}

public class UniffiContractVersionException : UniffiException
{
    public UniffiContractVersionException(string message)
        : base(message) { }
}

public class UniffiContractChecksumException : UniffiException
{
    public UniffiContractChecksumException(string message)
        : base(message) { }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E>
    where E : System.Exception
{
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler : CallStatusErrorHandler<UniffiException>
{
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf)
    {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers
{
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E : System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess())
        {
            return return_value;
        }
        else if (status.IsError())
        {
            throw errorHandler.Lift(status.error_buf);
        }
        else if (status.IsPanic())
        {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0)
            {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            }
            else
            {
                throw new PanicException("Rust panic");
            }
        }
        else
        {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E : System.Exception
    {
        _UniffiHelpers.RustCallWithError(
            errorHandler,
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback)
    {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }
}

static class FFIObjectUtil
{
    public static void DisposeAll(params Object?[] list)
    {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(Object? obj)
    {
        if (obj == null)
        {
            return;
        }

        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        var objType = obj.GetType();
        var typeCode = Type.GetTypeCode(objType);
        if (typeCode != TypeCode.Object)
        {
            return;
        }

        var genericArguments = objType.GetGenericArguments();
        if (genericArguments.Length == 0 && !objType.IsArray)
        {
            return;
        }

        if (obj is System.Collections.IDictionary objDictionary)
        {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all values as "double" and alike doesn't support interface "IDisposable"
            var valuesType = objType.GetGenericArguments()[1];
            var elementValuesTypeCode = Type.GetTypeCode(valuesType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in objDictionary.Values)
            {
                Dispose(value);
            }
        }
        else if (obj is System.Collections.IEnumerable listValues)
        {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
            var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
            var elementValuesTypeCode = Type.GetTypeCode(elementType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in listValues)
            {
                Dispose(value);
            }
        }
    }
}

// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException : System.Exception
{
    public StreamUnderflowException() { }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4)
    {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream)
    {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length)
    {
        if (stream.Length - stream.Position < length)
        {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action)
    {
        foreach (var item in items)
        {
            action(item);
        }
    }
}

class BigEndianStream
{
    Stream stream;

    public BigEndianStream(Stream stream)
    {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining()
    {
        return (stream.Length - Position) > 0;
    }

    public long Position
    {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer)
    {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);

    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);

    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value)
    {
        unsafe
        {
            WriteInt(*((int*)&value));
        }
    }

    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length)
    {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    // Reads a UTF-8 string of `length` bytes. Streams over RustBuffer memory
    // are decoded in place, avoiding an intermediate byte[] copy.
    public string ReadUtf8String(int length)
    {
        stream.CheckRemaining(length);
        if (length >= 0 && stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanRead)
        {
            unsafe
            {
                var start = unmanagedStream.PositionPointer;
                var result = System.Text.Encoding.UTF8.GetString(start, length);
                unmanagedStream.PositionPointer = start + length;
                return result;
            }
        }
        return System.Text.Encoding.UTF8.GetString(ReadBytes(length));
    }

    // Writes a big-endian length prefix followed by the UTF-8 bytes. Streams
    // over RustBuffer memory are encoded in place, avoiding an intermediate
    // byte[] copy.
    public void WriteUtf8String(string value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        if (stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanWrite)
        {
            // Bytes left for the string itself, after its 4-byte length prefix.
            var available = unmanagedStream.Length - unmanagedStream.Position - 4;

            // UTF-8 needs at most 3 bytes per UTF-16 code unit, so the exact
            // byte count is only computed when that worst case might not fit.
            if (
                available >= 0
                && (available >= 3L * value.Length || available >= System.Text.Encoding.UTF8.GetByteCount(value))
            )
            {
                unsafe
                {
                    var start = unmanagedStream.PositionPointer;
                    int length;
                    fixed (char* chars = value)
                    {
                        length = System.Text.Encoding.UTF8.GetBytes(
                            chars,
                            value.Length,
                            start + 4,
                            (int)Math.Min(available, int.MaxValue)
                        );
                    }
                    // The length is only known after encoding, so it goes into the
                    // 4 bytes reserved before the string, big-endian like WriteInt.
                    // `available >= 0` guarantees those bytes are inside the stream.
                    start[0] = (byte)(length >> 24);
                    start[1] = (byte)(length >> 16);
                    start[2] = (byte)(length >> 8);
                    start[3] = (byte)length;
                    unmanagedStream.PositionPointer = start + 4 + length;
                }
                return;
            }
        }
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        WriteInt(bytes.Length);
        WriteBytes(bytes);
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);

    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);

    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);

    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();

    public short ReadShort() => (short)ReadUShort();

    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat()
    {
        unsafe
        {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();

    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.

// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib
{
#else
static class _UniFFILib
{
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(ulong @data, sbyte @pollResult);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(ulong @handle);

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultVoid @result
    );

    static _UniFFILib()
    {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
    }

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_common_rustbuffer_alloc(ulong @size, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_common_rustbuffer_from_bytes(
        ForeignBytes @bytes,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rustbuffer_free(RustBuffer @buf, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_common_rustbuffer_reserve(
        RustBuffer @buf,
        ulong @additional,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_u8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    byte ffi_matrix_sdk_common_rust_future_complete_u8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_i8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    sbyte ffi_matrix_sdk_common_rust_future_complete_i8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_u16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ushort ffi_matrix_sdk_common_rust_future_complete_u16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_i16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    short ffi_matrix_sdk_common_rust_future_complete_i16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_u32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_common_rust_future_complete_u32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_i32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    int ffi_matrix_sdk_common_rust_future_complete_i32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_u64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong ffi_matrix_sdk_common_rust_future_complete_u64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_i64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    long ffi_matrix_sdk_common_rust_future_complete_i64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_f32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    float ffi_matrix_sdk_common_rust_future_complete_f32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_f64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    double ffi_matrix_sdk_common_rust_future_complete_f64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_rust_buffer(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_common_rust_future_complete_rust_buffer(
        ulong @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_poll_void(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_cancel_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_free_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_common_rust_future_complete_void(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_common_uniffi_contract_version();

    static void uniffiCheckContractApiVersion()
    {
        var scaffolding_contract_version = _UniFFILib.ffi_matrix_sdk_common_uniffi_contract_version();
        if (30 != scaffolding_contract_version)
        {
            throw new UniffiContractVersionException(
                $"Matrix.RustSdk.Bindings.Common: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`"
            );
        }
    }

    static void uniffiCheckApiChecksums() { }
}

// Public interface members begin here.

#pragma warning disable 8625

class FfiConverterString : FfiConverter<string, RustBuffer>
{
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value)
    {
        try
        {
            unsafe
            {
                return System.Text.Encoding.UTF8.GetString((byte*)value.data.ToPointer(), Convert.ToInt32(value.len));
            }
        }
        finally
        {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        return stream.ReadUtf8String(length);
    }

    public override RustBuffer Lower(string value)
    {
        var rustBuffer = RustBuffer.Alloc(System.Text.Encoding.UTF8.GetByteCount(value));
        try
        {
            unsafe
            {
                fixed (char* chars = value)
                {
                    System.Text.Encoding.UTF8.GetBytes(
                        chars,
                        value.Length,
                        (byte*)rustBuffer.data.ToPointer(),
                        Convert.ToInt32(rustBuffer.len)
                    );
                }
            }
            return rustBuffer;
        }
        catch
        {
            RustBuffer.Free(rustBuffer);
            throw;
        }
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value)
    {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream)
    {
        stream.WriteUtf8String(value);
    }
}

/// <summary>
/// Reason why a background task failed.
/// </summary>
public record BackgroundTaskFailureReason
{
    /// <summary>
    /// The task panicked.
    /// </summary>
    public record Panic(string? Message, string? PanicBacktrace) : BackgroundTaskFailureReason { }

    /// <summary>
    /// The task returned an error.
    /// </summary>
    public record Error(string ErrorValue) : BackgroundTaskFailureReason { }

    /// <summary>
    /// The task ended unexpectedly (for tasks expected to run forever).
    /// </summary>
    public record EarlyTermination : BackgroundTaskFailureReason { }
}

class FfiConverterTypeBackgroundTaskFailureReason : FfiConverterRustBuffer<BackgroundTaskFailureReason>
{
    public static FfiConverterRustBuffer<BackgroundTaskFailureReason> INSTANCE =
        new FfiConverterTypeBackgroundTaskFailureReason();

    public override BackgroundTaskFailureReason Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new BackgroundTaskFailureReason.Panic(
                    FfiConverterOptionalString.INSTANCE.Read(stream),
                    FfiConverterOptionalString.INSTANCE.Read(stream)
                );
            case 2:
                return new BackgroundTaskFailureReason.Error(FfiConverterString.INSTANCE.Read(stream));
            case 3:
                return new BackgroundTaskFailureReason.EarlyTermination();
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeBackgroundTaskFailureReason.Read()",
                        value
                    )
                );
        }
    }

    public override int AllocationSize(BackgroundTaskFailureReason value)
    {
        switch (value)
        {
            case BackgroundTaskFailureReason.Panic variant_value:
                return 4
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.Message)
                    + FfiConverterOptionalString.INSTANCE.AllocationSize(variant_value.PanicBacktrace);
            case BackgroundTaskFailureReason.Error variant_value:
                return 4 + FfiConverterString.INSTANCE.AllocationSize(variant_value.ErrorValue);
            case BackgroundTaskFailureReason.EarlyTermination variant_value:
                return 4;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeBackgroundTaskFailureReason.AllocationSize()",
                        value
                    )
                );
        }
    }

    public override void Write(BackgroundTaskFailureReason value, BigEndianStream stream)
    {
        switch (value)
        {
            case BackgroundTaskFailureReason.Panic variant_value:
                stream.WriteInt(1);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.Message, stream);
                FfiConverterOptionalString.INSTANCE.Write(variant_value.PanicBacktrace, stream);
                break;
            case BackgroundTaskFailureReason.Error variant_value:
                stream.WriteInt(2);
                FfiConverterString.INSTANCE.Write(variant_value.ErrorValue, stream);
                break;
            case BackgroundTaskFailureReason.EarlyTermination variant_value:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format(
                        "invalid enum value '{0}' in FfiConverterTypeBackgroundTaskFailureReason.Write()",
                        value
                    )
                );
        }
    }
}

/// <summary>
/// A machine-readable representation of the authenticity for a `ShieldState`.
/// </summary>
public enum ShieldStateCode : int
{
    /// <summary>
    /// Not enough information available to check the authenticity.
    /// </summary>
    AuthenticityNotGuaranteed,

    /// <summary>
    /// The sending device isn't yet known by the Client.
    /// </summary>
    UnknownDevice,

    /// <summary>
    /// The sending device hasn't been verified by the sender.
    /// </summary>
    UnsignedDevice,

    /// <summary>
    /// The sender hasn't been verified by the Client's user.
    /// </summary>
    UnverifiedIdentity,

    /// <summary>
    /// The sender was previously verified but changed their identity.
    /// </summary>
    VerificationViolation,

    /// <summary>
    /// The `sender` field on the event does not match the owner of the device
    /// that established the Megolm session.
    /// </summary>
    MismatchedSender,
}

class FfiConverterTypeShieldStateCode : FfiConverterRustBuffer<ShieldStateCode>
{
    public static FfiConverterTypeShieldStateCode INSTANCE = new FfiConverterTypeShieldStateCode();

    public override ShieldStateCode Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return ShieldStateCode.AuthenticityNotGuaranteed;
            case 2:
                return ShieldStateCode.UnknownDevice;
            case 3:
                return ShieldStateCode.UnsignedDevice;
            case 4:
                return ShieldStateCode.UnverifiedIdentity;
            case 5:
                return ShieldStateCode.VerificationViolation;
            case 6:
                return ShieldStateCode.MismatchedSender;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeShieldStateCode.Read()", value)
                );
        }
    }

    public override int AllocationSize(ShieldStateCode value)
    {
        return 4;
    }

    public override void Write(ShieldStateCode value, BigEndianStream stream)
    {
        switch (value)
        {
            case ShieldStateCode.AuthenticityNotGuaranteed:
                stream.WriteInt(1);
                break;
            case ShieldStateCode.UnknownDevice:
                stream.WriteInt(2);
                break;
            case ShieldStateCode.UnsignedDevice:
                stream.WriteInt(3);
                break;
            case ShieldStateCode.UnverifiedIdentity:
                stream.WriteInt(4);
                break;
            case ShieldStateCode.VerificationViolation:
                stream.WriteInt(5);
                break;
            case ShieldStateCode.MismatchedSender:
                stream.WriteInt(6);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeShieldStateCode.Write()", value)
                );
        }
    }
}

class FfiConverterOptionalString : FfiConverterRustBuffer<string?>
{
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream)
    {
        if (stream.ReadByte() == 0)
        {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value)
    {
        if (value == null)
        {
            return 1;
        }
        else
        {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream)
    {
        if (value == null)
        {
            stream.WriteByte(0);
        }
        else
        {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}
#pragma warning restore 8625
public static class MatrixSdkCommonMethods { }
