// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.11.1+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Matrix.RustSdk.Bindings.Base;

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer
{
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size)
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                var buffer = _UniFFILib.ffi_matrix_sdk_base_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
                if (buffer.data == IntPtr.Zero)
                {
                    throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
                }
                return buffer;
            }
        );
    }

    public static void Free(RustBuffer buffer)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.ffi_matrix_sdk_base_rustbuffer_free(buffer, ref status);
            }
        );
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len)));
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes
{
    public int length;
    public IntPtr data;
}

// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType>
{
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value)
    {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try
        {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        }
        catch
        {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf)
    {
        var stream = rbuf.AsStream();
        try
        {
            var item = Read(stream);
            if (stream.HasRemaining())
            {
                throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
            }
            return item;
        }
        finally
        {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType> : FfiConverter<CsType, RustBuffer>
{
    public override CsType Lift(RustBuffer value)
    {
        return LiftFromRustBuffer(value);
    }

    public override RustBuffer Lower(CsType value)
    {
        return LowerIntoRustBuffer(value);
    }
}

// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus
{
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess()
    {
        return code == 0;
    }

    public bool IsError()
    {
        return code == 1;
    }

    public bool IsPanic()
    {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException : System.Exception
{
    public UniffiException()
        : base() { }

    public UniffiException(string message)
        : base(message) { }
}

public class UndeclaredErrorException : UniffiException
{
    public UndeclaredErrorException(string message)
        : base(message) { }
}

public class PanicException : UniffiException
{
    public PanicException(string message)
        : base(message) { }
}

public class AllocationException : UniffiException
{
    public AllocationException(string message)
        : base(message) { }
}

public class InternalException : UniffiException
{
    public InternalException(string message)
        : base(message) { }
}

public class InvalidEnumException : InternalException
{
    public InvalidEnumException(string message)
        : base(message) { }
}

public class UniffiContractVersionException : UniffiException
{
    public UniffiContractVersionException(string message)
        : base(message) { }
}

public class UniffiContractChecksumException : UniffiException
{
    public UniffiContractChecksumException(string message)
        : base(message) { }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E>
    where E : System.Exception
{
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler : CallStatusErrorHandler<UniffiException>
{
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf)
    {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers
{
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E : System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess())
        {
            return return_value;
        }
        else if (status.IsError())
        {
            throw errorHandler.Lift(status.error_buf);
        }
        else if (status.IsPanic())
        {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0)
            {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            }
            else
            {
                throw new PanicException("Rust panic");
            }
        }
        else
        {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E : System.Exception
    {
        _UniffiHelpers.RustCallWithError(
            errorHandler,
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback)
    {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }
}

static class FFIObjectUtil
{
    public static void DisposeAll(params Object?[] list)
    {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(Object? obj)
    {
        if (obj == null)
        {
            return;
        }

        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        var objType = obj.GetType();
        var typeCode = Type.GetTypeCode(objType);
        if (typeCode != TypeCode.Object)
        {
            return;
        }

        var genericArguments = objType.GetGenericArguments();
        if (genericArguments.Length == 0 && !objType.IsArray)
        {
            return;
        }

        if (obj is System.Collections.IDictionary objDictionary)
        {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all values as "double" and alike doesn't support interface "IDisposable"
            var valuesType = objType.GetGenericArguments()[1];
            var elementValuesTypeCode = Type.GetTypeCode(valuesType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in objDictionary.Values)
            {
                Dispose(value);
            }
        }
        else if (obj is System.Collections.IEnumerable listValues)
        {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
            var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
            var elementValuesTypeCode = Type.GetTypeCode(elementType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in listValues)
            {
                Dispose(value);
            }
        }
    }
}

// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException : System.Exception
{
    public StreamUnderflowException() { }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4)
    {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream)
    {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length)
    {
        if (stream.Length - stream.Position < length)
        {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action)
    {
        foreach (var item in items)
        {
            action(item);
        }
    }
}

class BigEndianStream
{
    Stream stream;

    public BigEndianStream(Stream stream)
    {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining()
    {
        return (stream.Length - Position) > 0;
    }

    public long Position
    {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer)
    {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);

    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);

    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value)
    {
        unsafe
        {
            WriteInt(*((int*)&value));
        }
    }

    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length)
    {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    // Reads a UTF-8 string of `length` bytes. Streams over RustBuffer memory
    // are decoded in place, avoiding an intermediate byte[] copy.
    public string ReadUtf8String(int length)
    {
        stream.CheckRemaining(length);
        if (length >= 0 && stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanRead)
        {
            unsafe
            {
                var start = unmanagedStream.PositionPointer;
                var result = System.Text.Encoding.UTF8.GetString(start, length);
                unmanagedStream.PositionPointer = start + length;
                return result;
            }
        }
        return System.Text.Encoding.UTF8.GetString(ReadBytes(length));
    }

    // Writes a big-endian length prefix followed by the UTF-8 bytes. Streams
    // over RustBuffer memory are encoded in place, avoiding an intermediate
    // byte[] copy.
    public void WriteUtf8String(string value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        if (stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanWrite)
        {
            // Bytes left for the string itself, after its 4-byte length prefix.
            var available = unmanagedStream.Length - unmanagedStream.Position - 4;

            // UTF-8 needs at most 3 bytes per UTF-16 code unit, so the exact
            // byte count is only computed when that worst case might not fit.
            if (
                available >= 0
                && (available >= 3L * value.Length || available >= System.Text.Encoding.UTF8.GetByteCount(value))
            )
            {
                unsafe
                {
                    var start = unmanagedStream.PositionPointer;
                    int length;
                    fixed (char* chars = value)
                    {
                        length = System.Text.Encoding.UTF8.GetBytes(
                            chars,
                            value.Length,
                            start + 4,
                            (int)Math.Min(available, int.MaxValue)
                        );
                    }
                    // The length is only known after encoding, so it goes into the
                    // 4 bytes reserved before the string, big-endian like WriteInt.
                    // `available >= 0` guarantees those bytes are inside the stream.
                    start[0] = (byte)(length >> 24);
                    start[1] = (byte)(length >> 16);
                    start[2] = (byte)(length >> 8);
                    start[3] = (byte)length;
                    unmanagedStream.PositionPointer = start + 4 + length;
                }
                return;
            }
        }
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        WriteInt(bytes.Length);
        WriteBytes(bytes);
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);

    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);

    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);

    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();

    public short ReadShort() => (short)ReadUShort();

    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat()
    {
        unsafe
        {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();

    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.

// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib
{
#else
static class _UniFFILib
{
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(ulong @data, sbyte @pollResult);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(ulong @handle);

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultVoid @result
    );

    static _UniFFILib()
    {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
    }

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_base_rustbuffer_alloc(ulong @size, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_base_rustbuffer_from_bytes(ForeignBytes @bytes, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rustbuffer_free(RustBuffer @buf, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_base_rustbuffer_reserve(
        RustBuffer @buf,
        ulong @additional,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_u8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    byte ffi_matrix_sdk_base_rust_future_complete_u8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_i8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    sbyte ffi_matrix_sdk_base_rust_future_complete_i8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_u16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ushort ffi_matrix_sdk_base_rust_future_complete_u16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_i16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    short ffi_matrix_sdk_base_rust_future_complete_i16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_u32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_base_rust_future_complete_u32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_i32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    int ffi_matrix_sdk_base_rust_future_complete_i32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_u64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong ffi_matrix_sdk_base_rust_future_complete_u64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_i64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    long ffi_matrix_sdk_base_rust_future_complete_i64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_f32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    float ffi_matrix_sdk_base_rust_future_complete_f32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_f64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    double ffi_matrix_sdk_base_rust_future_complete_f64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_rust_buffer(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_base_rust_future_complete_rust_buffer(
        ulong @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_poll_void(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_cancel_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_free_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_base_rust_future_complete_void(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_base_uniffi_contract_version();

    static void uniffiCheckContractApiVersion()
    {
        var scaffolding_contract_version = _UniFFILib.ffi_matrix_sdk_base_uniffi_contract_version();
        if (30 != scaffolding_contract_version)
        {
            throw new UniffiContractVersionException(
                $"Matrix.RustSdk.Bindings.Base: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`"
            );
        }
    }

    static void uniffiCheckApiChecksums() { }
}

// Public interface members begin here.

#pragma warning disable 8625

class FfiConverterUInt64 : FfiConverter<ulong, ulong>
{
    public static FfiConverterUInt64 INSTANCE = new FfiConverterUInt64();

    public override ulong Lift(ulong value)
    {
        return value;
    }

    public override ulong Read(BigEndianStream stream)
    {
        return stream.ReadULong();
    }

    public override ulong Lower(ulong value)
    {
        return value;
    }

    public override int AllocationSize(ulong value)
    {
        return 8;
    }

    public override void Write(ulong value, BigEndianStream stream)
    {
        stream.WriteULong(value);
    }
}

class FfiConverterString : FfiConverter<string, RustBuffer>
{
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value)
    {
        try
        {
            unsafe
            {
                return System.Text.Encoding.UTF8.GetString((byte*)value.data.ToPointer(), Convert.ToInt32(value.len));
            }
        }
        finally
        {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        return stream.ReadUtf8String(length);
    }

    public override RustBuffer Lower(string value)
    {
        var rustBuffer = RustBuffer.Alloc(System.Text.Encoding.UTF8.GetByteCount(value));
        try
        {
            unsafe
            {
                fixed (char* chars = value)
                {
                    System.Text.Encoding.UTF8.GetBytes(
                        chars,
                        value.Length,
                        (byte*)rustBuffer.data.ToPointer(),
                        Convert.ToInt32(rustBuffer.len)
                    );
                }
            }
            return rustBuffer;
        }
        catch
        {
            RustBuffer.Free(rustBuffer);
            throw;
        }
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value)
    {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream)
    {
        stream.WriteUtf8String(value);
    }
}

class FfiConverterDuration : FfiConverterRustBuffer<TimeSpan>
{
    public static FfiConverterDuration INSTANCE = new FfiConverterDuration();

    // https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/TimeSpan.cs
    private const uint NanosecondsPerTick = 100;

    public override TimeSpan Read(BigEndianStream stream)
    {
        var seconds = stream.ReadULong();
        var nanoseconds = stream.ReadUInt();
        var ticks = seconds * TimeSpan.TicksPerSecond;
        ticks += nanoseconds / NanosecondsPerTick;
        return new TimeSpan(Convert.ToInt64(ticks));
    }

    public override int AllocationSize(TimeSpan value)
    {
        // 8 bytes for seconds, 4 bytes for nanoseconds
        return 12;
    }

    public override void Write(TimeSpan value, BigEndianStream stream)
    {
        stream.WriteULong(Convert.ToUInt64(value.Ticks / TimeSpan.TicksPerSecond));
        stream.WriteUInt(Convert.ToUInt32(value.Ticks % TimeSpan.TicksPerSecond * NanosecondsPerTick));
    }
}

/// <summary>
/// The retention policy for media content used by the [`MediaStore`].
///
/// [`EventCacheStore`]: crate::event_cache::store::EventCacheStore
/// </summary>
/// <param name="MaxCacheSize">
/// The maximum authorized size of the overall media cache, in bytes.
///
/// The cache size is defined as the sum of the sizes of all the (possibly
/// encrypted) media contents in the cache, excluding any metadata
/// associated with them.
///
/// If this is set and the cache size is bigger than this value, the oldest
/// media contents in the cache will be removed during a cleanup until the
/// cache size is below this threshold.
///
/// Note that it is possible for the cache size to temporarily exceed this
/// value between two cleanups.
///
/// Defaults to 400 MiB.
/// </param>
/// <param name="MaxFileSize">
/// The maximum authorized size of a single media content, in bytes.
///
/// The size of a media content is the size taken by the content in the
/// database, after it was possibly encrypted, so it might differ from the
/// initial size of the content.
///
/// The maximum authorized size of a single media content is actually the
/// lowest value between `max_cache_size` and `max_file_size`.
///
/// If it is set, media content bigger than the maximum size will not be
/// cached. If the maximum size changed after media content that exceeds the
/// new value was cached, the corresponding content will be removed
/// during a cleanup.
///
/// Defaults to 20 MiB.
/// </param>
/// <param name="LastAccessExpiry">
/// The duration after which unaccessed media content is considered
/// expired.
///
/// If this is set, media content whose last access is older than this
/// duration will be removed from the media cache during a cleanup.
///
/// Defaults to 60 days.
/// </param>
/// <param name="CleanupFrequency">
/// The duration between two automatic media cache cleanups.
///
/// If this is set, a cleanup will be triggered after the given duration
/// is elapsed, at the next call to the media cache API. If this is set to
/// zero, each call to the media cache API will trigger a cleanup. If this
/// is `None`, cleanups will only occur if they are triggered manually.
///
/// Defaults to running cleanups daily.
/// </param>
public record MediaRetentionPolicy(
    /// <summary>
    /// The maximum authorized size of the overall media cache, in bytes.
    ///
    /// The cache size is defined as the sum of the sizes of all the (possibly
    /// encrypted) media contents in the cache, excluding any metadata
    /// associated with them.
    ///
    /// If this is set and the cache size is bigger than this value, the oldest
    /// media contents in the cache will be removed during a cleanup until the
    /// cache size is below this threshold.
    ///
    /// Note that it is possible for the cache size to temporarily exceed this
    /// value between two cleanups.
    ///
    /// Defaults to 400 MiB.
    /// </summary>
    ulong? MaxCacheSize,
    /// <summary>
    /// The maximum authorized size of a single media content, in bytes.
    ///
    /// The size of a media content is the size taken by the content in the
    /// database, after it was possibly encrypted, so it might differ from the
    /// initial size of the content.
    ///
    /// The maximum authorized size of a single media content is actually the
    /// lowest value between `max_cache_size` and `max_file_size`.
    ///
    /// If it is set, media content bigger than the maximum size will not be
    /// cached. If the maximum size changed after media content that exceeds the
    /// new value was cached, the corresponding content will be removed
    /// during a cleanup.
    ///
    /// Defaults to 20 MiB.
    /// </summary>
    ulong? MaxFileSize,
    /// <summary>
    /// The duration after which unaccessed media content is considered
    /// expired.
    ///
    /// If this is set, media content whose last access is older than this
    /// duration will be removed from the media cache during a cleanup.
    ///
    /// Defaults to 60 days.
    /// </summary>
    TimeSpan? LastAccessExpiry,
    /// <summary>
    /// The duration between two automatic media cache cleanups.
    ///
    /// If this is set, a cleanup will be triggered after the given duration
    /// is elapsed, at the next call to the media cache API. If this is set to
    /// zero, each call to the media cache API will trigger a cleanup. If this
    /// is `None`, cleanups will only occur if they are triggered manually.
    ///
    /// Defaults to running cleanups daily.
    /// </summary>
    TimeSpan? CleanupFrequency
) { }

class FfiConverterTypeMediaRetentionPolicy : FfiConverterRustBuffer<MediaRetentionPolicy>
{
    public static FfiConverterTypeMediaRetentionPolicy INSTANCE = new FfiConverterTypeMediaRetentionPolicy();

    public override MediaRetentionPolicy Read(BigEndianStream stream)
    {
        return new MediaRetentionPolicy(
            MaxCacheSize: FfiConverterOptionalUInt64.INSTANCE.Read(stream),
            MaxFileSize: FfiConverterOptionalUInt64.INSTANCE.Read(stream),
            LastAccessExpiry: FfiConverterOptionalDuration.INSTANCE.Read(stream),
            CleanupFrequency: FfiConverterOptionalDuration.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(MediaRetentionPolicy value)
    {
        return 0
            + FfiConverterOptionalUInt64.INSTANCE.AllocationSize(value.MaxCacheSize)
            + FfiConverterOptionalUInt64.INSTANCE.AllocationSize(value.MaxFileSize)
            + FfiConverterOptionalDuration.INSTANCE.AllocationSize(value.LastAccessExpiry)
            + FfiConverterOptionalDuration.INSTANCE.AllocationSize(value.CleanupFrequency);
    }

    public override void Write(MediaRetentionPolicy value, BigEndianStream stream)
    {
        FfiConverterOptionalUInt64.INSTANCE.Write(value.MaxCacheSize, stream);
        FfiConverterOptionalUInt64.INSTANCE.Write(value.MaxFileSize, stream);
        FfiConverterOptionalDuration.INSTANCE.Write(value.LastAccessExpiry, stream);
        FfiConverterOptionalDuration.INSTANCE.Write(value.CleanupFrequency, stream);
    }
}

/// <summary>
/// An enum that defines what the [`BaseClient`] should consider a DM room.
/// </summary>
public enum DmRoomDefinition : int
{
    /// <summary>
    /// Standard Matrix spec definition: a room linked to a user in an
    /// `m.direct` event.
    /// </summary>
    MatrixSpec,

    /// <summary>
    /// A room that is direct, as per the spec but also contains at most 2
    /// active members.
    /// </summary>
    TwoMembers,
}

class FfiConverterTypeDmRoomDefinition : FfiConverterRustBuffer<DmRoomDefinition>
{
    public static FfiConverterTypeDmRoomDefinition INSTANCE = new FfiConverterTypeDmRoomDefinition();

    public override DmRoomDefinition Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return DmRoomDefinition.MatrixSpec;
            case 2:
                return DmRoomDefinition.TwoMembers;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeDmRoomDefinition.Read()", value)
                );
        }
    }

    public override int AllocationSize(DmRoomDefinition value)
    {
        return 4;
    }

    public override void Write(DmRoomDefinition value, BigEndianStream stream)
    {
        switch (value)
        {
            case DmRoomDefinition.MatrixSpec:
                stream.WriteInt(1);
                break;
            case DmRoomDefinition.TwoMembers:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeDmRoomDefinition.Write()", value)
                );
        }
    }
}

/// <summary>
/// Represents the state of a room encryption.
/// </summary>
public enum EncryptionState : int
{
    /// <summary>
    /// The room is encrypted.
    /// </summary>
    Encrypted,

    /// <summary>
    /// The room is not encrypted.
    /// </summary>
    NotEncrypted,

    /// <summary>
    /// The state of the room encryption is unknown, probably because the
    /// `/sync` did not provide all data needed to decide.
    /// </summary>
    Unknown,
}

class FfiConverterTypeEncryptionState : FfiConverterRustBuffer<EncryptionState>
{
    public static FfiConverterTypeEncryptionState INSTANCE = new FfiConverterTypeEncryptionState();

    public override EncryptionState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return EncryptionState.Encrypted;
            case 2:
                return EncryptionState.NotEncrypted;
            case 3:
                return EncryptionState.Unknown;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeEncryptionState.Read()", value)
                );
        }
    }

    public override int AllocationSize(EncryptionState value)
    {
        return 4;
    }

    public override void Write(EncryptionState value, BigEndianStream stream)
    {
        switch (value)
        {
            case EncryptionState.Encrypted:
                stream.WriteInt(1);
                break;
            case EncryptionState.NotEncrypted:
                stream.WriteInt(2);
                break;
            case EncryptionState.Unknown:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeEncryptionState.Write()", value)
                );
        }
    }
}

class FfiConverterOptionalUInt64 : FfiConverterRustBuffer<ulong?>
{
    public static FfiConverterOptionalUInt64 INSTANCE = new FfiConverterOptionalUInt64();

    public override ulong? Read(BigEndianStream stream)
    {
        if (stream.ReadByte() == 0)
        {
            return null;
        }
        return FfiConverterUInt64.INSTANCE.Read(stream);
    }

    public override int AllocationSize(ulong? value)
    {
        if (value == null)
        {
            return 1;
        }
        else
        {
            return 1 + FfiConverterUInt64.INSTANCE.AllocationSize((ulong)value);
        }
    }

    public override void Write(ulong? value, BigEndianStream stream)
    {
        if (value == null)
        {
            stream.WriteByte(0);
        }
        else
        {
            stream.WriteByte(1);
            FfiConverterUInt64.INSTANCE.Write((ulong)value, stream);
        }
    }
}

class FfiConverterOptionalDuration : FfiConverterRustBuffer<TimeSpan?>
{
    public static FfiConverterOptionalDuration INSTANCE = new FfiConverterOptionalDuration();

    public override TimeSpan? Read(BigEndianStream stream)
    {
        if (stream.ReadByte() == 0)
        {
            return null;
        }
        return FfiConverterDuration.INSTANCE.Read(stream);
    }

    public override int AllocationSize(TimeSpan? value)
    {
        if (value == null)
        {
            return 1;
        }
        else
        {
            return 1 + FfiConverterDuration.INSTANCE.AllocationSize((TimeSpan)value);
        }
    }

    public override void Write(TimeSpan? value, BigEndianStream stream)
    {
        if (value == null)
        {
            stream.WriteByte(0);
        }
        else
        {
            stream.WriteByte(1);
            FfiConverterDuration.INSTANCE.Write((TimeSpan)value, stream);
        }
    }
}
#pragma warning restore 8625
public static class MatrixSdkBaseMethods { }
