// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.11.1+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace Matrix.RustSdk.Bindings.Crypto;

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer
{
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size)
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                var buffer = _UniFFILib.ffi_matrix_sdk_crypto_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
                if (buffer.data == IntPtr.Zero)
                {
                    throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
                }
                return buffer;
            }
        );
    }

    public static void Free(RustBuffer buffer)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.ffi_matrix_sdk_crypto_rustbuffer_free(buffer, ref status);
            }
        );
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len)));
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes
{
    public int length;
    public IntPtr data;
}

// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType>
{
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value)
    {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try
        {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        }
        catch
        {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf)
    {
        var stream = rbuf.AsStream();
        try
        {
            var item = Read(stream);
            if (stream.HasRemaining())
            {
                throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
            }
            return item;
        }
        finally
        {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType> : FfiConverter<CsType, RustBuffer>
{
    public override CsType Lift(RustBuffer value)
    {
        return LiftFromRustBuffer(value);
    }

    public override RustBuffer Lower(CsType value)
    {
        return LowerIntoRustBuffer(value);
    }
}

// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus
{
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess()
    {
        return code == 0;
    }

    public bool IsError()
    {
        return code == 1;
    }

    public bool IsPanic()
    {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException : System.Exception
{
    public UniffiException()
        : base() { }

    public UniffiException(string message)
        : base(message) { }
}

public class UndeclaredErrorException : UniffiException
{
    public UndeclaredErrorException(string message)
        : base(message) { }
}

public class PanicException : UniffiException
{
    public PanicException(string message)
        : base(message) { }
}

public class AllocationException : UniffiException
{
    public AllocationException(string message)
        : base(message) { }
}

public class InternalException : UniffiException
{
    public InternalException(string message)
        : base(message) { }
}

public class InvalidEnumException : InternalException
{
    public InvalidEnumException(string message)
        : base(message) { }
}

public class UniffiContractVersionException : UniffiException
{
    public UniffiContractVersionException(string message)
        : base(message) { }
}

public class UniffiContractChecksumException : UniffiException
{
    public UniffiContractChecksumException(string message)
        : base(message) { }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E>
    where E : System.Exception
{
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler : CallStatusErrorHandler<UniffiException>
{
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf)
    {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers
{
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E : System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess())
        {
            return return_value;
        }
        else if (status.IsError())
        {
            throw errorHandler.Lift(status.error_buf);
        }
        else if (status.IsPanic())
        {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0)
            {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            }
            else
            {
                throw new PanicException("Rust panic");
            }
        }
        else
        {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E : System.Exception
    {
        _UniffiHelpers.RustCallWithError(
            errorHandler,
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback)
    {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback)
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                callback(ref status);
                return 0;
            }
        );
    }
}

static class FFIObjectUtil
{
    public static void DisposeAll(params Object?[] list)
    {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
    private static void Dispose(Object? obj)
    {
        if (obj == null)
        {
            return;
        }

        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
            return;
        }

        var objType = obj.GetType();
        var typeCode = Type.GetTypeCode(objType);
        if (typeCode != TypeCode.Object)
        {
            return;
        }

        var genericArguments = objType.GetGenericArguments();
        if (genericArguments.Length == 0 && !objType.IsArray)
        {
            return;
        }

        if (obj is System.Collections.IDictionary objDictionary)
        {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all values as "double" and alike doesn't support interface "IDisposable"
            var valuesType = objType.GetGenericArguments()[1];
            var elementValuesTypeCode = Type.GetTypeCode(valuesType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in objDictionary.Values)
            {
                Dispose(value);
            }
        }
        else if (obj is System.Collections.IEnumerable listValues)
        {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
            var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
            var elementValuesTypeCode = Type.GetTypeCode(elementType);
            if (elementValuesTypeCode != TypeCode.Object)
            {
                return;
            }
            foreach (var value in listValues)
            {
                Dispose(value);
            }
        }
    }
}

// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException : System.Exception
{
    public StreamUnderflowException() { }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4)
    {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream)
    {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToRead];
        stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte] * digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length)
    {
        if (stream.Length - stream.Position < length)
        {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action)
    {
        foreach (var item in items)
        {
            action(item);
        }
    }
}

class BigEndianStream
{
    Stream stream;

    public BigEndianStream(Stream stream)
    {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining()
    {
        return (stream.Length - Position) > 0;
    }

    public long Position
    {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer)
    {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);

    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);

    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value)
    {
        unsafe
        {
            WriteInt(*((int*)&value));
        }
    }

    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length)
    {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    // Reads a UTF-8 string of `length` bytes. Streams over RustBuffer memory
    // are decoded in place, avoiding an intermediate byte[] copy.
    public string ReadUtf8String(int length)
    {
        stream.CheckRemaining(length);
        if (length >= 0 && stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanRead)
        {
            unsafe
            {
                var start = unmanagedStream.PositionPointer;
                var result = System.Text.Encoding.UTF8.GetString(start, length);
                unmanagedStream.PositionPointer = start + length;
                return result;
            }
        }
        return System.Text.Encoding.UTF8.GetString(ReadBytes(length));
    }

    // Writes a big-endian length prefix followed by the UTF-8 bytes. Streams
    // over RustBuffer memory are encoded in place, avoiding an intermediate
    // byte[] copy.
    public void WriteUtf8String(string value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        if (stream is UnmanagedMemoryStream unmanagedStream && unmanagedStream.CanWrite)
        {
            // Bytes left for the string itself, after its 4-byte length prefix.
            var available = unmanagedStream.Length - unmanagedStream.Position - 4;

            // UTF-8 needs at most 3 bytes per UTF-16 code unit, so the exact
            // byte count is only computed when that worst case might not fit.
            if (
                available >= 0
                && (available >= 3L * value.Length || available >= System.Text.Encoding.UTF8.GetByteCount(value))
            )
            {
                unsafe
                {
                    var start = unmanagedStream.PositionPointer;
                    int length;
                    fixed (char* chars = value)
                    {
                        length = System.Text.Encoding.UTF8.GetBytes(
                            chars,
                            value.Length,
                            start + 4,
                            (int)Math.Min(available, int.MaxValue)
                        );
                    }
                    // The length is only known after encoding, so it goes into the
                    // 4 bytes reserved before the string, big-endian like WriteInt.
                    // `available >= 0` guarantees those bytes are inside the stream.
                    start[0] = (byte)(length >> 24);
                    start[1] = (byte)(length >> 16);
                    start[2] = (byte)(length >> 8);
                    start[3] = (byte)length;
                    unmanagedStream.PositionPointer = start + 4 + length;
                }
                return;
            }
        }
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        WriteInt(bytes.Length);
        WriteBytes(bytes);
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);

    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);

    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);

    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();

    public short ReadShort() => (short)ReadUShort();

    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat()
    {
        unsafe
        {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();

    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.

// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib
{
#else
static class _UniFFILib
{
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(ulong @data, sbyte @pollResult);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(ulong @handle);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(ulong @handle);

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI8 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI16 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultU64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultI64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF32 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultF64 @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );

    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,
        _UniFFILib.UniffiForeignFutureResultVoid @result
    );

    static _UniFFILib()
    {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
    }

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong uniffi_matrix_sdk_crypto_fn_clone_backupsecrets(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void uniffi_matrix_sdk_crypto_fn_free_backupsecrets(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong uniffi_matrix_sdk_crypto_fn_clone_crosssigningsecrets(
        ulong @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void uniffi_matrix_sdk_crypto_fn_free_crosssigningsecrets(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong uniffi_matrix_sdk_crypto_fn_clone_secretsbundle(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void uniffi_matrix_sdk_crypto_fn_free_secretsbundle(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_crypto_rustbuffer_alloc(ulong @size, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_crypto_rustbuffer_from_bytes(
        ForeignBytes @bytes,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rustbuffer_free(RustBuffer @buf, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_crypto_rustbuffer_reserve(
        RustBuffer @buf,
        ulong @additional,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_u8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_u8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    byte ffi_matrix_sdk_crypto_rust_future_complete_u8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_i8(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_i8(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    sbyte ffi_matrix_sdk_crypto_rust_future_complete_i8(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_u16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_u16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ushort ffi_matrix_sdk_crypto_rust_future_complete_u16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_i16(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_i16(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    short ffi_matrix_sdk_crypto_rust_future_complete_i16(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_u32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_u32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_crypto_rust_future_complete_u32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_i32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_i32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    int ffi_matrix_sdk_crypto_rust_future_complete_i32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_u64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_u64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    ulong ffi_matrix_sdk_crypto_rust_future_complete_u64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_i64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_i64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    long ffi_matrix_sdk_crypto_rust_future_complete_i64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_f32(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_f32(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    float ffi_matrix_sdk_crypto_rust_future_complete_f32(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_f64(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_f64(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    double ffi_matrix_sdk_crypto_rust_future_complete_f64(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_rust_buffer(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_rust_buffer(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    RustBuffer ffi_matrix_sdk_crypto_rust_future_complete_rust_buffer(
        ulong @handle,
        ref UniffiRustCallStatus _uniffi_out_err
    );

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_poll_void(ulong @handle, IntPtr @callback, ulong @callbackData);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_cancel_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_free_void(ulong @handle);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    void ffi_matrix_sdk_crypto_rust_future_complete_void(ulong @handle, ref UniffiRustCallStatus _uniffi_out_err);

#if NET8_0_OR_GREATER
    [LibraryImport("matrix_sdk_ffi")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("matrix_sdk_ffi", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
    uint ffi_matrix_sdk_crypto_uniffi_contract_version();

    static void uniffiCheckContractApiVersion()
    {
        var scaffolding_contract_version = _UniFFILib.ffi_matrix_sdk_crypto_uniffi_contract_version();
        if (30 != scaffolding_contract_version)
        {
            throw new UniffiContractVersionException(
                $"Matrix.RustSdk.Bindings.Crypto: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`"
            );
        }
    }

    static void uniffiCheckApiChecksums() { }
}

// Public interface members begin here.

#pragma warning disable 8625

class FfiConverterString : FfiConverter<string, RustBuffer>
{
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value)
    {
        try
        {
            unsafe
            {
                return System.Text.Encoding.UTF8.GetString((byte*)value.data.ToPointer(), Convert.ToInt32(value.len));
            }
        }
        finally
        {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream)
    {
        var length = stream.ReadInt();
        return stream.ReadUtf8String(length);
    }

    public override RustBuffer Lower(string value)
    {
        var rustBuffer = RustBuffer.Alloc(System.Text.Encoding.UTF8.GetByteCount(value));
        try
        {
            unsafe
            {
                fixed (char* chars = value)
                {
                    System.Text.Encoding.UTF8.GetBytes(
                        chars,
                        value.Length,
                        (byte*)rustBuffer.data.ToPointer(),
                        Convert.ToInt32(rustBuffer.len)
                    );
                }
            }
            return rustBuffer;
        }
        catch
        {
            RustBuffer.Free(rustBuffer);
            throw;
        }
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value)
    {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream)
    {
        stream.WriteUtf8String(value);
    }
}

/// <summary>
/// Enum for the algorithm-specific secrets for the room key backup.
/// </summary>
public interface IBackupSecrets { }

/// <summary>
/// Enum for the algorithm-specific secrets for the room key backup.
/// </summary>
public class BackupSecrets : IBackupSecrets, IDisposable
{
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public BackupSecrets(ulong pointer)
    {
        this.pointer = pointer;
    }

    ~BackupSecrets()
    {
        Destroy();
    }

    protected void FreeRustArcPtr()
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.uniffi_matrix_sdk_crypto_fn_free_backupsecrets(this.pointer, ref status);
            }
        );
    }

    protected ulong CloneRustArcPtr()
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                return _UniFFILib.uniffi_matrix_sdk_crypto_fn_clone_backupsecrets(this.pointer, ref status);
            }
        );
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter()
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L)
                throw new System.ObjectDisposedException(
                    String.Format("'{0}' object has already been destroyed", this.GetType().Name)
                );
            if (count == long.MaxValue)
                throw new System.OverflowException(
                    String.Format("'{0}' call counter would overflow", this.GetType().Name)
                );
        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter()
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0)
        {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try
        {
            action(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {
        IncrementCallCounter();
        try
        {
            return func(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }
}

class FfiConverterTypeBackupSecrets : FfiConverter<BackupSecrets, ulong>
{
    public static FfiConverterTypeBackupSecrets INSTANCE = new FfiConverterTypeBackupSecrets();

    public override ulong Lower(BackupSecrets value)
    {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override BackupSecrets Lift(ulong value)
    {
        return new BackupSecrets(value);
    }

    public override BackupSecrets Read(BigEndianStream stream)
    {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(BackupSecrets value)
    {
        return 8;
    }

    public override void Write(BackupSecrets value, BigEndianStream stream)
    {
        stream.WriteULong(Lower(value));
    }
}

/// <summary>
/// Data for the secrets bundle containing the cross-signing keys.
/// </summary>
public interface ICrossSigningSecrets { }

/// <summary>
/// Data for the secrets bundle containing the cross-signing keys.
/// </summary>
public class CrossSigningSecrets : ICrossSigningSecrets, IDisposable
{
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public CrossSigningSecrets(ulong pointer)
    {
        this.pointer = pointer;
    }

    ~CrossSigningSecrets()
    {
        Destroy();
    }

    protected void FreeRustArcPtr()
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.uniffi_matrix_sdk_crypto_fn_free_crosssigningsecrets(this.pointer, ref status);
            }
        );
    }

    protected ulong CloneRustArcPtr()
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                return _UniFFILib.uniffi_matrix_sdk_crypto_fn_clone_crosssigningsecrets(this.pointer, ref status);
            }
        );
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter()
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L)
                throw new System.ObjectDisposedException(
                    String.Format("'{0}' object has already been destroyed", this.GetType().Name)
                );
            if (count == long.MaxValue)
                throw new System.OverflowException(
                    String.Format("'{0}' call counter would overflow", this.GetType().Name)
                );
        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter()
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0)
        {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try
        {
            action(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {
        IncrementCallCounter();
        try
        {
            return func(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }
}

class FfiConverterTypeCrossSigningSecrets : FfiConverter<CrossSigningSecrets, ulong>
{
    public static FfiConverterTypeCrossSigningSecrets INSTANCE = new FfiConverterTypeCrossSigningSecrets();

    public override ulong Lower(CrossSigningSecrets value)
    {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override CrossSigningSecrets Lift(ulong value)
    {
        return new CrossSigningSecrets(value);
    }

    public override CrossSigningSecrets Read(BigEndianStream stream)
    {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(CrossSigningSecrets value)
    {
        return 8;
    }

    public override void Write(CrossSigningSecrets value, BigEndianStream stream)
    {
        stream.WriteULong(Lower(value));
    }
}

/// <summary>
/// Struct containing the bundle of secrets to fully activate a new device for
/// end-to-end encryption.
/// </summary>
public interface ISecretsBundle { }

/// <summary>
/// Struct containing the bundle of secrets to fully activate a new device for
/// end-to-end encryption.
/// </summary>
public class SecretsBundle : ISecretsBundle, IDisposable
{
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public SecretsBundle(ulong pointer)
    {
        this.pointer = pointer;
    }

    ~SecretsBundle()
    {
        Destroy();
    }

    protected void FreeRustArcPtr()
    {
        _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                _UniFFILib.uniffi_matrix_sdk_crypto_fn_free_secretsbundle(this.pointer, ref status);
            }
        );
    }

    protected ulong CloneRustArcPtr()
    {
        return _UniffiHelpers.RustCall(
            (ref UniffiRustCallStatus status) =>
            {
                return _UniFFILib.uniffi_matrix_sdk_crypto_fn_clone_secretsbundle(this.pointer, ref status);
            }
        );
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter()
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L)
                throw new System.ObjectDisposedException(
                    String.Format("'{0}' object has already been destroyed", this.GetType().Name)
                );
            if (count == long.MaxValue)
                throw new System.OverflowException(
                    String.Format("'{0}' call counter would overflow", this.GetType().Name)
                );
        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter()
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0)
        {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try
        {
            action(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {
        IncrementCallCounter();
        try
        {
            return func(CloneRustArcPtr());
        }
        finally
        {
            DecrementCallCounter();
        }
    }
}

class FfiConverterTypeSecretsBundle : FfiConverter<SecretsBundle, ulong>
{
    public static FfiConverterTypeSecretsBundle INSTANCE = new FfiConverterTypeSecretsBundle();

    public override ulong Lower(SecretsBundle value)
    {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override SecretsBundle Lift(ulong value)
    {
        return new SecretsBundle(value);
    }

    public override SecretsBundle Read(BigEndianStream stream)
    {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(SecretsBundle value)
    {
        return 8;
    }

    public override void Write(SecretsBundle value, BigEndianStream stream)
    {
        stream.WriteULong(Lower(value));
    }
}

/// <summary>
/// Settings for decrypting messages
/// </summary>
/// <param name="SenderDeviceTrustRequirement">
/// The trust level in the sender's device that is required to decrypt the
/// event. If the sender's device is not sufficiently trusted,
/// [`MegolmError::SenderIdentityNotTrusted`] will be returned.
/// </param>
public record DecryptionSettings(
    /// <summary>
    /// The trust level in the sender's device that is required to decrypt the
    /// event. If the sender's device is not sufficiently trusted,
    /// [`MegolmError::SenderIdentityNotTrusted`] will be returned.
    /// </summary>
    TrustRequirement SenderDeviceTrustRequirement
) { }

class FfiConverterTypeDecryptionSettings : FfiConverterRustBuffer<DecryptionSettings>
{
    public static FfiConverterTypeDecryptionSettings INSTANCE = new FfiConverterTypeDecryptionSettings();

    public override DecryptionSettings Read(BigEndianStream stream)
    {
        return new DecryptionSettings(
            SenderDeviceTrustRequirement: FfiConverterTypeTrustRequirement.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(DecryptionSettings value)
    {
        return 0 + FfiConverterTypeTrustRequirement.INSTANCE.AllocationSize(value.SenderDeviceTrustRequirement);
    }

    public override void Write(DecryptionSettings value, BigEndianStream stream)
    {
        FfiConverterTypeTrustRequirement.INSTANCE.Write(value.SenderDeviceTrustRequirement, stream);
    }
}

/// <summary>
/// Strategy to collect the devices that should receive room keys for the
/// current discussion.
/// </summary>
public enum CollectStrategy : int
{
    /// <summary>
    /// Share with all (unblacklisted) devices.
    ///
    /// Not recommended, per the guidance of [MSC4153].
    ///
    /// (Used by Element X and Element Web in the legacy, non-"exclude insecure
    /// devices" mode.)
    ///
    /// [MSC4153]: https://github.com/matrix-org/matrix-doc/pull/4153
    /// </summary>
    AllDevices,

    /// <summary>
    /// Share with all devices, except errors for *verified* users cause sharing
    /// to fail with an error.
    ///
    /// In this strategy, if a verified user has an unsigned device,
    /// key sharing will fail with a
    /// [`SessionRecipientCollectionError::VerifiedUserHasUnsignedDevice`].
    /// If a verified user has replaced their identity, key
    /// sharing will fail with a
    /// [`SessionRecipientCollectionError::VerifiedUserChangedIdentity`].
    ///
    /// Otherwise, keys are shared with unsigned devices as normal.
    ///
    /// Once the problematic devices are blacklisted or whitelisted the
    /// caller can retry to share a second time.
    ///
    /// Not recommended, per the guidance of [MSC4153].
    ///
    /// [MSC4153]: https://github.com/matrix-org/matrix-doc/pull/4153
    /// </summary>
    ErrorOnVerifiedUserProblem,

    /// <summary>
    /// Share based on identity. Only distribute to devices signed by their
    /// owner. If a user has no published identity he will not receive
    /// any room keys.
    ///
    /// This is the recommended strategy: it is compliant with the guidance of
    /// [MSC4153].
    ///
    /// (Used by Element Web and Element X in the "exclude insecure devices"
    /// mode.)
    ///
    /// [MSC4153]: https://github.com/matrix-org/matrix-doc/pull/4153
    /// </summary>
    IdentityBasedStrategy,

    /// <summary>
    /// Only share keys with devices that we "trust". A device is trusted if any
    /// of the following is true:
    /// - It was manually marked as trusted.
    /// - It was marked as verified via interactive verification.
    /// - It is signed by its owner identity, and this identity has been
    /// trusted via interactive verification.
    /// - It is the current own device of the user.
    ///
    /// This strategy is compliant with [MSC4153], but is probably too strict
    /// for normal use.
    ///
    /// (Used by Element Web when "only send messages to verified users" is
    /// enabled.)
    ///
    /// [MSC4153]: https://github.com/matrix-org/matrix-doc/pull/4153
    /// </summary>
    OnlyTrustedDevices,
}

class FfiConverterTypeCollectStrategy : FfiConverterRustBuffer<CollectStrategy>
{
    public static FfiConverterTypeCollectStrategy INSTANCE = new FfiConverterTypeCollectStrategy();

    public override CollectStrategy Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return CollectStrategy.AllDevices;
            case 2:
                return CollectStrategy.ErrorOnVerifiedUserProblem;
            case 3:
                return CollectStrategy.IdentityBasedStrategy;
            case 4:
                return CollectStrategy.OnlyTrustedDevices;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeCollectStrategy.Read()", value)
                );
        }
    }

    public override int AllocationSize(CollectStrategy value)
    {
        return 4;
    }

    public override void Write(CollectStrategy value, BigEndianStream stream)
    {
        switch (value)
        {
            case CollectStrategy.AllDevices:
                stream.WriteInt(1);
                break;
            case CollectStrategy.ErrorOnVerifiedUserProblem:
                stream.WriteInt(2);
                break;
            case CollectStrategy.IdentityBasedStrategy:
                stream.WriteInt(3);
                break;
            case CollectStrategy.OnlyTrustedDevices:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeCollectStrategy.Write()", value)
                );
        }
    }
}

/// <summary>
/// The state of an identity - verified, pinned etc.
/// </summary>
public enum IdentityState : int
{
    /// <summary>
    /// The user is verified with us
    /// </summary>
    Verified,

    /// <summary>
    /// Either this is the first identity we have seen for this user, or the
    /// user has acknowledged a change of identity explicitly e.g. by
    /// clicking OK on a notification.
    /// </summary>
    Pinned,

    /// <summary>
    /// The user's identity has changed since it was pinned. The user should be
    /// notified about this and given the opportunity to acknowledge the
    /// change, which will make the new identity pinned.
    /// When the user acknowledges the change, the app should call
    /// [`crate::OtherUserIdentity::pin_current_master_key`].
    /// </summary>
    PinViolation,

    /// <summary>
    /// The user's identity has changed, and before that it was verified. This
    /// is a serious problem. The user can either verify again to make this
    /// identity verified, or withdraw verification
    /// [`UserIdentity::withdraw_verification`] to make it pinned.
    /// </summary>
    VerificationViolation,
}

class FfiConverterTypeIdentityState : FfiConverterRustBuffer<IdentityState>
{
    public static FfiConverterTypeIdentityState INSTANCE = new FfiConverterTypeIdentityState();

    public override IdentityState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return IdentityState.Verified;
            case 2:
                return IdentityState.Pinned;
            case 3:
                return IdentityState.PinViolation;
            case 4:
                return IdentityState.VerificationViolation;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeIdentityState.Read()", value)
                );
        }
    }

    public override int AllocationSize(IdentityState value)
    {
        return 4;
    }

    public override void Write(IdentityState value, BigEndianStream stream)
    {
        switch (value)
        {
            case IdentityState.Verified:
                stream.WriteInt(1);
                break;
            case IdentityState.Pinned:
                stream.WriteInt(2);
                break;
            case IdentityState.PinViolation:
                stream.WriteInt(3);
                break;
            case IdentityState.VerificationViolation:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeIdentityState.Write()", value)
                );
        }
    }
}

/// <summary>
/// The local trust state of a device.
/// </summary>
public enum LocalTrust : int
{
    /// <summary>
    /// The device has been verified and is trusted.
    /// </summary>
    Verified,

    /// <summary>
    /// The device been blacklisted from communicating.
    /// </summary>
    BlackListed,

    /// <summary>
    /// The trust state of the device is being ignored.
    /// </summary>
    Ignored,

    /// <summary>
    /// The trust state is unset.
    /// </summary>
    Unset,
}

class FfiConverterTypeLocalTrust : FfiConverterRustBuffer<LocalTrust>
{
    public static FfiConverterTypeLocalTrust INSTANCE = new FfiConverterTypeLocalTrust();

    public override LocalTrust Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return LocalTrust.Verified;
            case 2:
                return LocalTrust.BlackListed;
            case 3:
                return LocalTrust.Ignored;
            case 4:
                return LocalTrust.Unset;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeLocalTrust.Read()", value)
                );
        }
    }

    public override int AllocationSize(LocalTrust value)
    {
        return 4;
    }

    public override void Write(LocalTrust value, BigEndianStream stream)
    {
        switch (value)
        {
            case LocalTrust.Verified:
                stream.WriteInt(1);
                break;
            case LocalTrust.BlackListed:
                stream.WriteInt(2);
                break;
            case LocalTrust.Ignored:
                stream.WriteInt(3);
                break;
            case LocalTrust.Unset:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeLocalTrust.Write()", value)
                );
        }
    }
}

/// <summary>
/// Error type for the decoding of the [`QrCodeData`].
/// </summary>
public class LoginQrCodeDecodeException : UniffiException
{
    LoginQrCodeDecodeException(string message)
        : base(message) { }

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.

    /// <summary>
    /// The QR code data is no long enough, it's missing some fields.
    /// </summary>
    public class NotEnoughData : LoginQrCodeDecodeException
    {
        public NotEnoughData(string message)
            : base(message) { }
    }

    /// <summary>
    /// One of the URLs in the QR code data is not a valid UTF-8 encoded string.
    /// </summary>
    public class NotUtf8 : LoginQrCodeDecodeException
    {
        public NotUtf8(string message)
            : base(message) { }
    }

    /// <summary>
    /// One of the URLs in the QR code data could not be parsed.
    /// </summary>
    public class UrlParse : LoginQrCodeDecodeException
    {
        public UrlParse(string message)
            : base(message) { }
    }

    /// <summary>
    /// The QR code data contains an invalid intent, we expect the login
    /// intent or the reciprocate intent.
    /// </summary>
    public class InvalidIntent : LoginQrCodeDecodeException
    {
        public InvalidIntent(string message)
            : base(message) { }
    }

    /// <summary>
    /// The QR code data contains an unsupported type.
    /// </summary>
    public class InvalidType : LoginQrCodeDecodeException
    {
        public InvalidType(string message)
            : base(message) { }
    }

    /// <summary>
    /// The base64 encoded variant of the QR code data is not a valid base64
    /// string.
    /// </summary>
    public class Base64 : LoginQrCodeDecodeException
    {
        public Base64(string message)
            : base(message) { }
    }

    /// <summary>
    /// The QR code data doesn't contain the expected `MATRIX` prefix.
    /// </summary>
    public class InvalidPrefix : LoginQrCodeDecodeException
    {
        public InvalidPrefix(string message)
            : base(message) { }
    }
}

class FfiConverterTypeLoginQrCodeDecodeError
    : FfiConverterRustBuffer<LoginQrCodeDecodeException>,
        CallStatusErrorHandler<LoginQrCodeDecodeException>
{
    public static FfiConverterTypeLoginQrCodeDecodeError INSTANCE = new FfiConverterTypeLoginQrCodeDecodeError();

    public override LoginQrCodeDecodeException Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return new LoginQrCodeDecodeException.NotEnoughData(FfiConverterString.INSTANCE.Read(stream));
            case 2:
                return new LoginQrCodeDecodeException.NotUtf8(FfiConverterString.INSTANCE.Read(stream));
            case 3:
                return new LoginQrCodeDecodeException.UrlParse(FfiConverterString.INSTANCE.Read(stream));
            case 4:
                return new LoginQrCodeDecodeException.InvalidIntent(FfiConverterString.INSTANCE.Read(stream));
            case 5:
                return new LoginQrCodeDecodeException.InvalidType(FfiConverterString.INSTANCE.Read(stream));
            case 6:
                return new LoginQrCodeDecodeException.Base64(FfiConverterString.INSTANCE.Read(stream));
            case 7:
                return new LoginQrCodeDecodeException.InvalidPrefix(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(
                    String.Format("invalid error value '{0}' in FfiConverterTypeLoginQrCodeDecodeError.Read()", value)
                );
        }
    }

    public override int AllocationSize(LoginQrCodeDecodeException value)
    {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(LoginQrCodeDecodeException value, BigEndianStream stream)
    {
        switch (value)
        {
            case LoginQrCodeDecodeException.NotEnoughData:
                stream.WriteInt(1);
                break;
            case LoginQrCodeDecodeException.NotUtf8:
                stream.WriteInt(2);
                break;
            case LoginQrCodeDecodeException.UrlParse:
                stream.WriteInt(3);
                break;
            case LoginQrCodeDecodeException.InvalidIntent:
                stream.WriteInt(4);
                break;
            case LoginQrCodeDecodeException.InvalidType:
                stream.WriteInt(5);
                break;
            case LoginQrCodeDecodeException.Base64:
                stream.WriteInt(6);
                break;
            case LoginQrCodeDecodeException.InvalidPrefix:
                stream.WriteInt(7);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid error value '{0}' in FfiConverterTypeLoginQrCodeDecodeError.Write()", value)
                );
        }
    }
}

/// <summary>
/// The intent of the device that generated/displayed the QR code.
///
/// The QR code login mechanism supports both, the new device, as well as the
/// existing device to display the QR code.
///
/// The different intents have an explicit one-byte identifier which gets added
/// to the QR code data.
/// </summary>
public enum QrCodeIntent : int
{
    /// <summary>
    /// Enum variant for the case where the new device is displaying the QR
    /// code.
    /// </summary>
    Login,

    /// <summary>
    /// Enum variant for the case where the existing device is displaying the QR
    /// code.
    /// </summary>
    Reciprocate,
}

class FfiConverterTypeQrCodeIntent : FfiConverterRustBuffer<QrCodeIntent>
{
    public static FfiConverterTypeQrCodeIntent INSTANCE = new FfiConverterTypeQrCodeIntent();

    public override QrCodeIntent Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return QrCodeIntent.Login;
            case 2:
                return QrCodeIntent.Reciprocate;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeQrCodeIntent.Read()", value)
                );
        }
    }

    public override int AllocationSize(QrCodeIntent value)
    {
        return 4;
    }

    public override void Write(QrCodeIntent value, BigEndianStream stream)
    {
        switch (value)
        {
            case QrCodeIntent.Login:
                stream.WriteInt(1);
                break;
            case QrCodeIntent.Reciprocate:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeQrCodeIntent.Write()", value)
                );
        }
    }
}

/// <summary>
/// The result of a signature check.
/// </summary>
public enum SignatureState : int
{
    /// <summary>
    /// The signature is missing.
    /// </summary>
    Missing,

    /// <summary>
    /// The signature is invalid.
    /// </summary>
    Invalid,

    /// <summary>
    /// The signature is valid but the device or user identity that created the
    /// signature is not trusted.
    /// </summary>
    ValidButNotTrusted,

    /// <summary>
    /// The signature is valid and the device or user identity that created the
    /// signature is trusted.
    /// </summary>
    ValidAndTrusted,
}

class FfiConverterTypeSignatureState : FfiConverterRustBuffer<SignatureState>
{
    public static FfiConverterTypeSignatureState INSTANCE = new FfiConverterTypeSignatureState();

    public override SignatureState Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return SignatureState.Missing;
            case 2:
                return SignatureState.Invalid;
            case 3:
                return SignatureState.ValidButNotTrusted;
            case 4:
                return SignatureState.ValidAndTrusted;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeSignatureState.Read()", value)
                );
        }
    }

    public override int AllocationSize(SignatureState value)
    {
        return 4;
    }

    public override void Write(SignatureState value, BigEndianStream stream)
    {
        switch (value)
        {
            case SignatureState.Missing:
                stream.WriteInt(1);
                break;
            case SignatureState.Invalid:
                stream.WriteInt(2);
                break;
            case SignatureState.ValidButNotTrusted:
                stream.WriteInt(3);
                break;
            case SignatureState.ValidAndTrusted:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeSignatureState.Write()", value)
                );
        }
    }
}

/// <summary>
/// The trust level in the sender's device that is required to decrypt an
/// event.
/// </summary>
public enum TrustRequirement : int
{
    /// <summary>
    /// Decrypt events from everyone regardless of trust.
    ///
    /// Not recommended, per the guidance of [MSC4153].
    ///
    /// [MSC4153]: https://github.com/matrix-org/matrix-doc/pull/4153
    /// </summary>
    Untrusted,

    /// <summary>
    /// Only decrypt events from cross-signed devices or legacy sessions (Megolm
    /// sessions created before we started collecting trust information).
    /// </summary>
    CrossSignedOrLegacy,

    /// <summary>
    /// Only decrypt events from cross-signed devices.
    /// </summary>
    CrossSigned,
}

class FfiConverterTypeTrustRequirement : FfiConverterRustBuffer<TrustRequirement>
{
    public static FfiConverterTypeTrustRequirement INSTANCE = new FfiConverterTypeTrustRequirement();

    public override TrustRequirement Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return TrustRequirement.Untrusted;
            case 2:
                return TrustRequirement.CrossSignedOrLegacy;
            case 3:
                return TrustRequirement.CrossSigned;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTrustRequirement.Read()", value)
                );
        }
    }

    public override int AllocationSize(TrustRequirement value)
    {
        return 4;
    }

    public override void Write(TrustRequirement value, BigEndianStream stream)
    {
        switch (value)
        {
            case TrustRequirement.Untrusted:
                stream.WriteInt(1);
                break;
            case TrustRequirement.CrossSignedOrLegacy:
                stream.WriteInt(2);
                break;
            case TrustRequirement.CrossSigned:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeTrustRequirement.Write()", value)
                );
        }
    }
}

/// <summary>
/// Our best guess at the reason why an event can't be decrypted.
/// </summary>
public enum UtdCause : int
{
    /// <summary>
    /// We don't have an explanation for why this UTD happened - it is probably
    /// a bug, or a network split between the two homeservers.
    ///
    /// For example:
    ///
    /// - the keys for this event are missing, but a key storage backup exists
    /// and is working, so we should be able to find the keys in the backup.
    ///
    /// - the keys for this event are missing, and a key storage backup exists
    /// on the server, but that backup is not working on this client even
    /// though this device is verified.
    /// </summary>
    Unknown,

    /// <summary>
    /// We are missing the keys for this event, and the event was sent when we
    /// were not a member of the room (or invited).
    /// </summary>
    SentBeforeWeJoined,

    /// <summary>
    /// The message was sent by a user identity we have not verified, but the
    /// user was previously verified.
    /// </summary>
    VerificationViolation,

    /// <summary>
    /// The [`crate::TrustRequirement`] requires that the sending device be
    /// signed by its owner, and it was not.
    /// </summary>
    UnsignedDevice,

    /// <summary>
    /// The [`crate::TrustRequirement`] requires that the sending device be
    /// signed by its owner, and we were unable to securely find the device.
    ///
    /// This could be because the device has since been deleted, because we
    /// haven't yet downloaded it from the server, or because the session
    /// data was obtained from an insecure source (imported from a file,
    /// obtained from a legacy (asymmetric) backup, unsafe key forward, etc.)
    /// </summary>
    UnknownDevice,

    /// <summary>
    /// We are missing the keys for this event, but it is a "device-historical"
    /// message and there is no key storage backup on the server, presumably
    /// because the user has turned it off.
    ///
    /// Device-historical means that the message was sent before the current
    /// device existed (but the current user was probably a member of the room
    /// at the time the message was sent). Not to
    /// be confused with pre-join or pre-invite messages (see
    /// [`UtdCause::SentBeforeWeJoined`] for that).
    ///
    /// Expected message to user: "History is not available on this device".
    /// </summary>
    HistoricalMessageAndBackupIsDisabled,

    /// <summary>
    /// The keys for this event are intentionally withheld.
    ///
    /// The sender has refused to share the key because our device does not meet
    /// the sender's security requirements.
    /// </summary>
    WithheldForUnverifiedOrInsecureDevice,

    /// <summary>
    /// The keys for this event are missing, likely because the sender was
    /// unable to share them (e.g., failure to establish an Olm 1:1
    /// channel). Alternatively, the sender may have deliberately excluded
    /// this device by cherry-picking and blocking it, in which case, no action
    /// can be taken on our side.
    /// </summary>
    WithheldBySender,

    /// <summary>
    /// We are missing the keys for this event, but it is a "device-historical"
    /// message, and even though a key storage backup does exist, we can't use
    /// it because our device is unverified.
    ///
    /// Device-historical means that the message was sent before the current
    /// device existed (but the current user was probably a member of the room
    /// at the time the message was sent). Not to
    /// be confused with pre-join or pre-invite messages (see
    /// [`UtdCause::SentBeforeWeJoined`] for that).
    ///
    /// Expected message to user: "You need to verify this device".
    /// </summary>
    HistoricalMessageAndDeviceIsUnverified,
}

class FfiConverterTypeUtdCause : FfiConverterRustBuffer<UtdCause>
{
    public static FfiConverterTypeUtdCause INSTANCE = new FfiConverterTypeUtdCause();

    public override UtdCause Read(BigEndianStream stream)
    {
        var value = stream.ReadInt();
        switch (value)
        {
            case 1:
                return UtdCause.Unknown;
            case 2:
                return UtdCause.SentBeforeWeJoined;
            case 3:
                return UtdCause.VerificationViolation;
            case 4:
                return UtdCause.UnsignedDevice;
            case 5:
                return UtdCause.UnknownDevice;
            case 6:
                return UtdCause.HistoricalMessageAndBackupIsDisabled;
            case 7:
                return UtdCause.WithheldForUnverifiedOrInsecureDevice;
            case 8:
                return UtdCause.WithheldBySender;
            case 9:
                return UtdCause.HistoricalMessageAndDeviceIsUnverified;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeUtdCause.Read()", value)
                );
        }
    }

    public override int AllocationSize(UtdCause value)
    {
        return 4;
    }

    public override void Write(UtdCause value, BigEndianStream stream)
    {
        switch (value)
        {
            case UtdCause.Unknown:
                stream.WriteInt(1);
                break;
            case UtdCause.SentBeforeWeJoined:
                stream.WriteInt(2);
                break;
            case UtdCause.VerificationViolation:
                stream.WriteInt(3);
                break;
            case UtdCause.UnsignedDevice:
                stream.WriteInt(4);
                break;
            case UtdCause.UnknownDevice:
                stream.WriteInt(5);
                break;
            case UtdCause.HistoricalMessageAndBackupIsDisabled:
                stream.WriteInt(6);
                break;
            case UtdCause.WithheldForUnverifiedOrInsecureDevice:
                stream.WriteInt(7);
                break;
            case UtdCause.WithheldBySender:
                stream.WriteInt(8);
                break;
            case UtdCause.HistoricalMessageAndDeviceIsUnverified:
                stream.WriteInt(9);
                break;
            default:
                throw new InternalException(
                    String.Format("invalid enum value '{0}' in FfiConverterTypeUtdCause.Write()", value)
                );
        }
    }
}

#pragma warning restore 8625
public static class MatrixSdkCryptoMethods { }
