<Project Sdk="Microsoft.NET.Sdk">
  <!-- convenience package depending on the native libraries for all platforms -->
  <PropertyGroup>
    <PackageId>Matrix.RustSdk.Bindings.Native.All</PackageId>
    <PackageDescription>Unofficial native matrix-rust-sdk libraries for Matrix.RustSdk.Bindings, for all supported platforms. Not affiliated with The Matrix.org Foundation.</PackageDescription>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
    <ExactProjectReferenceVersions>true</ExactProjectReferenceVersions>
    <!-- the package intentionally only consists of dependencies -->
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Matrix.RustSdk.Bindings.Native.Linux/Matrix.RustSdk.Bindings.Native.Linux.csproj" />
    <ProjectReference Include="../Matrix.RustSdk.Bindings.Native.Windows/Matrix.RustSdk.Bindings.Native.Windows.csproj" />
    <ProjectReference Include="../Matrix.RustSdk.Bindings.Native.MacOS/Matrix.RustSdk.Bindings.Native.MacOS.csproj" />
  </ItemGroup>
</Project>
