using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Matrix.RustSdk.Generators;

/// <summary>
/// Implements the <c>static partial</c> extension methods marked with <c>[VectorDiffConversion]</c>: converts a diff
/// enum of the bindings to <c>Matrix.RustSdk.VectorDiff&lt;T&gt;</c>, see <see cref="VectorDiffShape"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class VectorDiffConversionGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Matrix.RustSdk.Subscriptions.VectorDiffConversionAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<GeneratorResult> results = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            static (node, _) => node is MethodDeclarationSyntax,
            static (attributeContext, _) => Generate((IMethodSymbol)attributeContext.TargetSymbol)
        );

        context.RegisterSourceOutput(results, static (output, result) => result.AddTo(output));
    }

    private static GeneratorResult Generate(IMethodSymbol declaration)
    {
        Location? location = declaration.Locations.FirstOrDefault();
        if (ValidDeclarationItem(declaration) is not { } item)
        {
            return GeneratorResult.Error(
                Diagnostics.InvalidConversion,
                location,
                "a diff conversion has to be a static partial extension method of a top level, non generic class "
                    + "with a single parameter, returning Matrix.RustSdk.VectorDiff<T>"
            );
        }

        ITypeSymbol diff = declaration.Parameters[0].Type;
        VectorDiffShape? shape = VectorDiffShape.Analyze(diff, out string? error);
        if (shape is not null && !SymbolEqualityComparer.IncludeNullability.Equals(shape.Item, item))
        {
            error = $"it is a diff of {shape.Item.ToDisplayString()}";
        }
        if (error is not null || shape is null)
        {
            return GeneratorResult.Error(
                Diagnostics.NotADiff,
                location,
                diff.ToDisplayString(),
                item.ToDisplayString(),
                error ?? ""
            );
        }

        string value = SubscriptionGenerator.Identifier(declaration.Parameters[0]);
        CodeWriter code = new();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line();
        if (!declaration.ContainingNamespace.IsGlobalNamespace)
        {
            code.Line($"namespace {declaration.ContainingNamespace.ToDisplayString()};");
            code.Line();
        }
        code.Line($"static partial class {declaration.ContainingType.Name}");
        code.Open();
        code.Line(
            $"{SubscriptionGenerator.Accessibility(declaration)} static partial "
                + $"{declaration.ReturnType.ToDisplayString(SubscriptionGenerator.TypeFormat)} {declaration.Name}("
        );
        code.Indented(new[] { "this " + SubscriptionGenerator.Parameter(declaration.Parameters[0]) });
        code.Line(")");
        code.Open();
        code.Line($"global::System.ArgumentNullException.ThrowIfNull({value}, nameof({value}));");
        string[] lines = shape.RenderSwitch(value, SubscriptionGenerator.TypeFormat).ToArray();
        lines[0] = "return " + lines[0];
        lines[lines.Length - 1] += ";";
        foreach (string line in lines)
        {
            code.Line(line);
        }
        code.Close();
        code.Close();

        string hintName = $"{declaration.ContainingType.ToDisplayString()}.{declaration.Name}.{diff.Name}.g.cs";
        return new GeneratorResult(hintName, code.ToString(), null);
    }

    /// <summary>
    /// <c>static partial VectorDiff&lt;T&gt; Name(this Diff diff)</c> in a top level, non generic class.
    /// </summary>
    private static ITypeSymbol? ValidDeclarationItem(IMethodSymbol declaration) =>
        declaration.IsPartialDefinition
        && declaration.IsExtensionMethod
        && !declaration.IsGenericMethod
        && declaration.ContainingType.ContainingType is null
        && !declaration.ContainingType.IsGenericType
        && declaration.Parameters.Length == 1
        && declaration.Parameters[0].RefKind == RefKind.None
            ? VectorDiffShape.VectorDiffItem(declaration.ReturnType)
            : null;
}
