<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageDescription>Unofficial native matrix-rust-sdk libraries for Matrix.RustSdk.Bindings on macOS (x64 and arm64). Not affiliated with The Matrix.org Foundation.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <NativeLibrary
      Include="$(NativeLibrariesDirectory)osx-x64/native/libmatrix_sdk_ffi.dylib"
      PackagePath="runtimes/osx-x64/native/"
    />
    <NativeLibrary
      Include="$(NativeLibrariesDirectory)osx-arm64/native/libmatrix_sdk_ffi.dylib"
      PackagePath="runtimes/osx-arm64/native/"
    />
  </ItemGroup>
  <Import Project="../Native.targets" />
</Project>
