#!/usr/bin/env bash

set -eo pipefail

# cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs --tag v0.6.0+v0.25.0

echo "=> Generating bindings..."

BASE_DIRECTORY=$(pwd)
UNIFFI_CONFIG=src/Matrix.RustSdk.Bindings/uniffi.toml
RUST_SDK_DIRECTORY=external/matrix-rust-sdk
LIBRARY_FILE=target/debug/libmatrix_sdk_ffi.so
UNIFFI_OUTPUT=external/matrix-rust-sdk/generated-bindings/matrix_sdk_ffi.cs
OUTPUT=src/Matrix.RustSdk.Bindings/Bindings.cs
FILE_HEADER="// <auto-generated/>\n#nullable enable"

cp $UNIFFI_CONFIG $RUST_SDK_DIRECTORY/bindings/matrix-sdk-ffi/uniffi.toml
cd $RUST_SDK_DIRECTORY

uniffi-bindgen-cs $LIBRARY_FILE --library --out-dir generated-bindings

echo "=> Moving generated bindings to the Matrix.RustSdk.Bindings project..."
cd $BASE_DIRECTORY
mv $UNIFFI_OUTPUT $OUTPUT

echo "=> Cleaning up matrix-rust-sdk repository..."
cd $RUST_SDK_DIRECTORY
git restore .

echo "=> Adding file header..."
cd $BASE_DIRECTORY
sed -i "1s;^;$FILE_HEADER;" $OUTPUT
