#!/usr/bin/env bash

set -eo pipefail

# cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs.git --tag v0.5.0+v0.24.0

echo "Generating bindings..."

UNIFFI_CONFIG=src/Matrix.RustSdk.Bindings/uniffi.toml
UDL_FILE=external/matrix-rust-sdk/bindings/matrix-sdk-ffi/src/api.udl
UNIFFI_OUTPUT=external/matrix-rust-sdk/bindings/matrix-sdk-ffi/src/matrix_sdk_ffi.cs
OUTPUT=src/Matrix.RustSdk.Bindings/Bindings.cs
FILE_HEADER="// <auto-generated/>\n#nullable enable"

uniffi-bindgen-cs $UDL_FILE --config $UNIFFI_CONFIG
mv $UNIFFI_OUTPUT $OUTPUT

# Add file header
sed -i "1s;^;$FILE_HEADER;" $OUTPUT
