<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Matrix.RustSdk</PackageId>
    <PackageDescription>A C# wrapper for the matrix-rust-sdk crate.</PackageDescription>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.35.0.4138">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Matrix.RustSdk.Bindings\Matrix.RustSdk.Bindings.csproj" />
  </ItemGroup>
</Project>
