<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Matrix.RustSdk</PackageId>
    <PackageDescription>An unofficial C# wrapper for matrix-rust-sdk. Not affiliated with The Matrix.org Foundation.</PackageDescription>
    <!-- not published until it provides helpers on top of the bindings -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Matrix.RustSdk.Bindings\Matrix.RustSdk.Bindings.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- unit tests of the runtime part of the subscriptions -->
    <InternalsVisibleTo Include="Matrix.RustSdk.Tests" />
    <ProjectReference
      Include="..\Matrix.RustSdk.Generators\Matrix.RustSdk.Generators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
